project_id = "teeojvlqulhghditoakc"

[functions.generate-leads]
verify_jwt = false

[functions.research-company]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.submit-order]
verify_jwt = false

[functions.create-account]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.update-subscription-quantity]
verify_jwt = false

[functions.felsokning-ai]
verify_jwt = true
