// ALVA-SPEC-060 · Español.
//
// Las instrucciones van en infinitivo, sin dirigirse al usuario:
// «Fotografiar el cuentakilómetros», no «Fotografíe el cuentakilómetros».
// Es el registro de las instrucciones técnicas y respeta ALVA-SPEC-001 §7
// — el sistema informa de un estado, no se dirige al operario.
//
// `granskat: false`: la interfaz está traducida; el texto de
// procedimiento no está revisado por un especialista. Véase index.mjs.

export const ES = {
  // ---- Grados de evidencia ------------------------------------------------
  "evidens.E1": "Observación",
  "evidens.E2": "Fotografía",
  "evidens.E3": "Vídeo con sonido",
  "evidens.E4": "Medición, instrumento calibrado",
  "evidens.E5": "Documento",
  "evidens.ej_kalibrerad": "calibración ausente o caducada",
  "evidens.ej_angivet": "instrumento no indicado",
  "evidens.ej_fotograferad": "introducido, no fotografiado",

  // ---- El control de cierre -----------------------------------------------
  "grind.objekt": "Identificación del vehículo u objeto verificada",
  "grind.historik": "Historial del vehículo comprobado, o su omisión justificada",
  "grind.historik.nekad": "Una comprobación de historial rechazada exige que se indique el motivo.",
  "grind.historik.saknas": "No hay ninguna comprobación de historial documentada.",
  "grind.matarstallning.ingaende": "Kilometraje de entrada fotografiado",
  "grind.matarstallning.utgaende": "Kilometraje de salida fotografiado",
  "grind.matarstallning.saknas": "No hay ningún kilometraje documentado.",
  "grind.matarstallning.ej_foto":
    "El kilometraje está introducido pero no fotografiado. Fotografiar el cuentakilómetros, o indicar por qué no es posible.",
  "grind.reproducering": "Verificación del síntoma: reproducido, o documentado como no reproducible",
  "grind.felorsak": "Análisis de la causa raíz documentado",
  "grind.atgard": "Acción correctiva documentada, o su ausencia justificada",
  "grind.atgard.saknas": "No se ha documentado ni una acción realizada ni un motivo de su ausencia.",
  "grind.kundbeslut": "Decisión del cliente sobre la propuesta: registrada",
  "grind.kundbeslut.avbojt": "Trabajo realizado pese a una propuesta rechazada",
  "grind.kundbeslut.avbojt.detalj":
    "El cliente rechazó la propuesta, pero hay trabajo documentado como realizado.",
  "grind.kvalitetskontroll": "Control de calidad realizado — síntoma verificado como resuelto",
  "grind.kontroller": "Puntos de control de la metodología: evidencia, o exención documentada",
  "grind.foton": "Hay fotografías para los puntos de control que las exigen",
  "grind.slutsats": "Conclusión (ALVA-RULE-200)",
  "grind.hogvolt.behorighet": "Habilitación de alta tensión confirmada",
  "grind.hogvolt.spanningslos": "Vehículo sin tensión según el procedimiento del fabricante, ausencia de tensión verificada mediante medición",
  "grind.regelpaket": "La firma del paquete de reglas no coincide — cierre bloqueado.",
  "grind.regelpaket.osignerat": "Se utiliza un paquete de reglas externo sin firma — cierre bloqueado.",
  "grind.evidens": "Nivel de evidencia superior a E0",
  "grind.evidens.saknas": "No hay ninguna evidencia de ningún tipo en el registro.",
  "grind.foton.detalj": "{kontroller} puntos de control exigen fotografía, {foton} fotografías en el registro.",
  "grind.anmarkning.bevis": "Los hallazgos llevan prueba visual",
  "grind.anmarkning.saknas": "Un fallo reparado debe constar como hallazgo",
  "grind.anmarkning.saknas.detalj": "Se realizó un trabajo y se estableció una causa raíz, pero ningún control está marcado como hallazgo. Lo reparado no aparece entonces en el registro como algo encontrado.",
  "grind.sparr.ej_uppfyllt": "El requisito de seguridad no se cumple.",
  "grind.sparr.kringgangen": "Una condición de seguridad se respondió y no se cumplió. No puede omitirse cambiando de metodología — cúmplala, o si la metodología era errónea, la pregunta de seguridad no debería haberse respondido bajo ella.",
  "grind.arendetyp.okant": "Requisito desconocido en el paquete de reglas: {krav}",
  "grind.arendetyp.krav": "Requisito para este tipo de expediente: {krav}",
  "grind.sakerhet": "Nivel de confianza dentro de lo que sustenta la evidencia",
  "grind.sakerhet.detalj": "La confianza indicada ({niva}) supera lo que sustenta la evidencia ({tak}). Añadir evidencia que la sustente, o bajar el nivel — la incertidumbre honesta es información.",
  "grind.eskalering": "Escalaciones técnicas respondidas",
  "grind.eskalering.detalj": "Hay una escalación abierta ({referens}). Esperar la respuesta y documentarla antes de cerrar el expediente.",


  // ---- La conclusión (ALVA-RULE-200) --------------------------------------
  "slutsats.rubrik": "Conclusión",
  "slutsats.konstaterat": "Qué se ha establecido",
  "slutsats.evidens": "Qué evidencia lo sustenta",
  "slutsats.avfardat": "Qué hipótesis se han descartado, y por qué",
  "slutsats.osakert": "Qué sigue siendo incierto",
  "slutsats.ickesvar": "Eso no es una respuesta. Indicar qué se ha establecido y qué evidencia lo sustenta.",
  "slutsats.falt.motivering": "Justificación",
  "slutsats.falt.motivering_ej": "Motivo por el que no se pudo establecer la causa",
  "slutsats.falt.uteslutet": "Alternativas descartadas",
  "slutsats.falt.kvarstaende": "Incertidumbre restante",
  "slutsats.falt.atgardsval": "Elección de la acción",
  "slutsats.saknas": "Falta el campo «{falt}».",
  "slutsats.ickesvar.falt": "{falt}: «{text}» no es un motivo. Indicar qué se aplica realmente, y por qué.",
  "slutsats.for_kort": "El campo «{falt}» es demasiado corto ({langd} de al menos {minsta} caracteres) para poder revisarse después.",
  "slutsats.utan_varfor": "{falt} indica el qué, pero no el porqué. Vincular la conclusión con la evidencia — ¿qué hay en ella que la sustente?",
  "slutsats.utan_slutsats": "El expediente no se puede cerrar sin una conclusión. Indicar por qué la conclusión se desprende de la evidencia.",
  "slutsats.hypotes_obemott": "La hipótesis «{text}» figura en el registro pero no se aborda. Indicar por qué se descartó, o por qué sigue abierta.",


  // ---- Flujo del expediente -----------------------------------------------
  "arende.nytt": "Nuevo expediente",
  "arende.oppna": "Expedientes abiertos",
  "arende.avslutade": "Expedientes cerrados",
  "arende.avsluta": "Cerrar el expediente",
  "arende.avslutat": "Expediente cerrado",
  "arende.kan_ej_avslutas": "El expediente todavía no se puede cerrar",
  "arende.hinder": "Pendiente antes del cierre",
  "arende.overlamna": "Transferir",
  "arende.ansvarig": "Responsable",

  // ---- Comprobación previa ------------------------------------------------
  "pre.rubrik": "Comprobación previa — antes de iniciar el trabajo",
  "pre.historik.fraga":
    "¿Se ha comprobado el historial del vehículo? (trabajos anteriores, averías recurrentes, TSB, campañas)",
  "pre.historik.ja": "Sí — comprobado",
  "pre.historik.nej": "No",
  "pre.historik.skal": "Motivo por el que no se ha comprobado el historial (obligatorio)",
  "pre.historik.relevant": "Trabajos anteriores relevantes (opcional — cadena causal)",
  "pre.matarstallning": "Kilometraje",
  "pre.fotografera": "Fotografiar el cuadro de instrumentos",
  "pre.felbeskrivning": "Descripción de la avería según el cliente verificada",
  "pre.observationer": "¿Algo más en la recepción?",

  // ---- Acciones -----------------------------------------------------------
  "handling.spara": "Guardar",
  "handling.avbryt": "Cancelar",
  "handling.fortsatt": "Continuar",
  "handling.tillbaka": "Atrás",
  "handling.dokumentera": "Documentar",
  "handling.fotografera": "Fotografiar",
  "handling.spela_in": "Grabar vídeo",
  "handling.undantag": "Documentar una exención",
  "handling.undantag.skal": "Motivo de la exención (obligatorio)",
  "handling.exportera": "Exportar",
  "handling.skriv_ut": "Imprimir",

  // ---- Medición -----------------------------------------------------------
  "matning.varde": "Valor",
  "matning.enhet": "Unidad",
  "matning.matdon": "Instrumento",
  "matning.matdon.valj": "Seleccionar instrumento",
  "matning.matdon.okant": "Instrumento desconocido. Registrarlo antes de guardar la medición.",
  "matning.kalibrerad_till": "Calibrado hasta",

  // ---- Informe ------------------------------------------------------------
  "rapport.rubrik": "Informe del expediente",
  "rapport.sammanfattning": "Resumen",
  "rapport.evidens": "Evidencia",
  "rapport.atgarder": "Acciones",
  "rapport.harledd":
    "Derivado del registro del expediente. Las observaciones y las mediciones se presentan sin conclusiones que carezcan de sustento.",

  // ---- Idioma -------------------------------------------------------------
  "sprak.valj": "Idioma",
  "sprak.granskat": "Revisado",
  "sprak.ogranskat": "Sin revisar",
  "sprak.tackning": "{procent} % de la interfaz",

  "metodik.ogranskad":
    "El texto de procedimiento no ha sido revisado por un especialista técnico en {sprak}. Los pasos y los puntos de control se muestran en inglés cuando no existe una traducción revisada — una traducción sin revisar de una instrucción de seguridad es peor que una en lengua extranjera, porque no parece extranjera.",
  "metodik.pa_engelska": "Mostrado en inglés — no hay traducción revisada en {sprak}",

  // ---- Sitio público (webb.) ---------------------------------------------
  "webb.nav.oversikt": "Visión general",
  "webb.ansok": "Solicitar cuenta",
  "webb.loggain": "Iniciar sesión",
  "webb.fot.impressum": "Aviso legal",
  "webb.fot.dataskydd": "Privacidad",
  "webb.fot.villkor": "Condiciones",
  "webb.fot.tillganglighet": "Accesibilidad",
  "webb.fot.sprak": "Idiomas",
  "webb.fot.utgavor": "Notas de versión",

  "webb.hero.position": "Plataforma de diagnóstico guiado",
  "webb.hero.definition": "Procedimientos de diagnóstico estandarizados para una localización de averías repetible y verificable.",

  "webb.metod.etikett": "Metodología",
  "webb.metod.rubrik": "El modelo ALVA",
  "webb.metod.ingress":
    "ALVA es un método estandarizado de análisis, localización, verificación y acción sistemáticos. Cada decisión es trazable, cada conclusión verificable, cada acción reproducible.",
  "webb.fas.analysis.syfte": "Reunir evidencia.",
  "webb.fas.analysis.avgransning": "Solo hechos. En esta fase no se recogen hipótesis.",
  "webb.fas.localization.syfte": "Aislar la avería.",
  "webb.fas.localization.avgransning": "Delimitar la zona. La causa aún no está establecida.",
  "webb.fas.verification.syfte": "Confirmar la causa raíz.",
  "webb.fas.verification.avgransning": "Se verifica la causa — no el síntoma.",
  "webb.fas.action.syfte": "Ejecutar la acción correctiva.",
  "webb.fas.action.avgransning": "Resultado verificado y documentado. De lo contrario, la fase está incompleta.",

  "webb.drift.etikett": "Operativa",
  "webb.drift.rubrik": "Cómo funciona",
  "webb.drift.s1.rubrik": "Crear la organización",
  "webb.drift.s1.text": "El registro se envía y se revisa.",
  "webb.drift.s2.rubrik": "Los usuarios reciben cuentas",
  "webb.drift.s2.text": "El administrador de la organización asigna los roles.",
  "webb.drift.s3.rubrik": "Procedimientos de diagnóstico guiados",
  "webb.drift.s3.text": "Cada expediente sigue un procedimiento definido.",
  "webb.drift.s4.rubrik": "Verificación",
  "webb.drift.s4.text": "La causa raíz se confirma antes de la acción correctiva.",
  "webb.drift.s5.rubrik": "Documentación",
  "webb.drift.s5.text": "El informe se genera a partir del registro del expediente.",
  "webb.drift.s6.rubrik": "Mejora continua",
  "webb.drift.s6.text": "Los resultados verificados refinan los procedimientos posteriores.",

  "webb.larande.etikett": "Capacidad",
  "webb.larande.rubrik": "Aprendizaje de la organización",
  "webb.larande.p1":
    "La plataforma refina continuamente los procedimientos de diagnóstico con la experiencia operativa verificada de su propia organización.",
  "webb.larande.p2":
    "Cada diagnóstico completado alimenta la guía posterior. Solo se usan resultados verificados — un expediente cerrado sin causa raíz confirmada no aporta nada, por diseño.",
  "webb.larande.p3":
    "La base de conocimiento pertenece a la organización. Se deriva de sus casos, sus procedimientos y su documentación, y no se agrega entre clientes.",
  "webb.larande.block": "Derivada de",
  "webb.larande.k1": "Causas raíz verificadas",
  "webb.larande.k2": "Acciones correctivas confirmadas",
  "webb.larande.k3": "Categorías de averías recurrentes",
  "webb.larande.k4": "Registros de procedimientos completados",
  "webb.larande.k5": "Documentación de la organización",

  "webb.rapport.etikett": "Informes",
  "webb.rapport.rubrik": "Informe trimestral de mejora",
  "webb.rapport.ingress":
    "Una vez al trimestre, la plataforma responde seis preguntas sobre el propio trabajo del taller. Cada respuesta se deriva del registro de expedientes — nada se estima y no se pregunta a nadie.",
  "webb.rapport.f1": "¿Qué averías diagnosticamos ahora bien a la primera?",
  "webb.rapport.f2": "¿Con qué frecuencia la causa sospechada resulta ser la real?",
  "webb.rapport.f3": "¿Qué averías vuelven una y otra vez en la flota?",
  "webb.rapport.f4": "¿Qué pasos del procedimiento se omiten, y por qué?",
  "webb.rapport.f5": "¿Qué sabe el taller ahora que no sabía el trimestre pasado?",
  "webb.rapport.f6": "¿Se cierran, verifican y documentan los expedientes — o solo se cierran?",

  "webb.pris.etikett": "Comercial",
  "webb.pris.rubrik": "Licencias",
  "webb.pris.komponent": "Componente",
  "webb.pris.grund": "Base",
  "webb.pris.plattform": "Licencia de plataforma",
  "webb.pris.plattform.grund": "Por organización, anual",
  "webb.pris.anvandare": "Licencias de usuario",
  "webb.pris.anvandare.grund": "Por usuario activo, mensual",
  "webb.pris.moduler": "Módulos de empresa",
  "webb.pris.moduler.grund": "Opcionales, por módulo",
  "webb.pris.betalning": "Sin pago en línea. Sin alta de suscripción. La facturación sigue a la revisión de la solicitud.",
  "webb.pris.aktivering": "Secuencia de activación",
  "webb.pris.a1": "La organización envía el registro.",
  "webb.pris.a2": "La solicitud se revisa.",
  "webb.pris.a3": "Se emite la factura.",
  "webb.pris.a4": "Se registra el pago.",
  "webb.pris.a5": "La organización se activa.",
  "webb.pris.a6": "Los usuarios adicionales se facturan mensualmente.",

  "webb.kallor.etikett": "Infraestructura",
  "webb.kallor.rubrik": "Infraestructura operativa de conocimiento",
  "webb.kallor.p1":
    "ALVA usa las fuentes de conocimiento autorizadas propias de la organización. La arquitectura es neutral respecto al proveedor: cada fuente implementa la misma interfaz y no se presupone ningún proveedor.",
  "webb.kallor.p2":
    "Una instalación beta trabaja solo con documentación interna. Los proveedores externos se habilitan más adelante mediante conectores separados, sin cambios en el núcleo de la plataforma.",
  "webb.kallor.block": "Orden de resolución de fuentes",
  "webb.kallor.k1": "Procedimientos internos de la empresa",
  "webb.kallor.k2": "Documentación OEM",
  "webb.kallor.k3": "Boletines técnicos",
  "webb.kallor.k4": "Información de garantía",
  "webb.kallor.k5": "Manuales de taller",
  "webb.kallor.k6": "Histórico de diagnósticos verificados",
  "webb.kallor.k7": "Buenas prácticas de la organización",

  "webb.login.etikett": "Acceso",
  "webb.login.demo":
    "Este acceso no autentica nada. Escriba cualquier cosa en Correo y Contraseña y pulse Iniciar sesión — no hace falta cuenta, y el portal detrás presenta datos de ejemplo fijos. Conectada a una instancia de la plataforma, esta página se autentica contra ella, y el portal queda cerrado sin una sesión válida.",
  "webb.login.losenord": "Contraseña",
  "webb.login.ofullstandigt": "Autenticación incompleta. Se requieren correo y contraseña.",
  "webb.login.misslyckades": "Autenticación fallida.",
  "webb.login.logga_in": "Iniciar sesión",
  "webb.login.loggar_in": "Iniciando sesión",
  "webb.login.glomt": "Contraseña olvidada",

  "webb.ansokan.etikett": "Registro",
  "webb.ansokan.demo":
    "No se envía nada. Enviar este formulario no guarda nada, no avisa a nadie y no crea ninguna solicitud — todavía no hay ningún proceso de recepción detrás. La descripción de abajo indica cómo está previsto que funcione el registro, no lo que ocurre hoy.",
  "webb.ansokan.avsikt": "Funcionamiento previsto: las solicitudes se revisan manualmente y en esta fase no se cobra ningún pago.",
  "webb.falt.foretag": "Empresa",
  "webb.falt.orgnummer": "Número de registro mercantil",
  "webb.falt.kontakt": "Persona de contacto",
  "webb.falt.epost": "Correo electrónico",
  "webb.falt.telefon": "Teléfono",
  "webb.falt.tekniker": "Número de técnicos",
  "webb.falt.bransch": "Sector",
  "webb.falt.land": "País",
  "webb.falt.anvandare": "Número previsto de usuarios",
  "webb.falt.noteringar": "Observaciones",
  "webb.falt.kravs": "(obligatorio)",
  "webb.ansokan.skicka": "Enviar la solicitud",
  "webb.ansokan.mottagen.etikett": "Solicitud",
  "webb.ansokan.mottagen": "Enviada",
  "webb.ansokan.mottagen.demo":
    "No se transmitió nada y no se avisó a nadie. La referencia de abajo se calculó en su navegador a partir de lo que escribió y no existe en ningún otro lugar — desaparecerá al cerrar esta página.",
  "webb.ansokan.status": "Estado",
  "webb.ansokan.referens": "Referencia",
  "webb.ansokan.granskning":
    "Las solicitudes se revisan manualmente. La factura se emite al aprobarse. La organización se activa cuando se registra el pago.",

  "webb.sprak.etikett": "Localización",
  "webb.sprak.rubrik": "Idiomas",
  "webb.sprak.ingress":
    "El inglés es el idioma predeterminado y el idioma fuente. Le siguen nueve traducciones. Lo que la plataforma no hace es afirmar que una interfaz traducida signifique un método traducido.",
  "webb.sprak.princip.etikett": "Principio",
  "webb.sprak.princip.rubrik": "Dos clases de texto",
  "webb.sprak.granssnitt.rubrik": "Texto de interfaz",
  "webb.sprak.granssnitt.beteckning": "Recurre al inglés en silencio",
  "webb.sprak.granssnitt.text":
    "Etiquetas, botones, estados. Finito, rara vez cambia. Una cadena en inglés que llega a un usuario alemán es una molestia, no un peligro — así que una traducción ausente recurre al inglés sin comentario.",
  "webb.sprak.metodik.rubrik": "Texto de procedimiento",
  "webb.sprak.metodik.beteckning": "Nunca recurre al inglés en silencio",
  "webb.sprak.metodik.text":
    "Instrucciones para trabajar en un vehículo. Aquí una traducción sin revisar es peor que una en lengua extranjera — porque el inglés parece extranjero, mientras que una mala traducción parece una instrucción. Se muestra en inglés y se marca, con el idioma nombrado.",
  "webb.sprak.invariant":
    "El método en sí nunca se traduce. Los nombres de fase y las palabras de estado son la estructura de ALVA y se leen igual en todos los países, de modo que un auditor puede leer un expediente rumano y uno alemán sin saber en qué idioma trabaja el taller.",
  "webb.sprak.tackning.etikett": "Cobertura",
  "webb.sprak.tackning.rubrik": "Qué está traducido, y qué está revisado",
  "webb.sprak.kolumn.sprak": "Idioma",
  "webb.sprak.kolumn.granssnitt": "Interfaz",
  "webb.sprak.kolumn.granskat": "Método revisado por un especialista",
  "webb.sprak.granskat.ja": "Sí",
  "webb.sprak.granskat.nej": "No — texto de procedimiento en inglés",
  "webb.sprak.matt":
    "La cobertura de la interfaz se mide, no se estima: una prueba hace fallar la compilación si falta alguna clave en algún idioma. El estado de revisión es una afirmación sobre personas, no sobre archivos, y se fija a mano.",
  "webb.sprak.kallsprak":
    "El texto de procedimiento en inglés es una traducción de la fuente sueca y aún no ha sido leído por un especialista que ejerza el oficio. Se le exige lo mismo que a los otros nueve idiomas, y aquí se hace sobre él la misma declaración en lugar de exceptuarlo en silencio por ser la fuente.",
  "webb.sprak.bevis.etikett": "Verificación",
  "webb.sprak.bevis.rubrik": "Las frases que detienen un expediente",
  "webb.sprak.bevis.ingress":
    "Estas son las frases que impiden a un técnico cerrar un expediente. Una negativa que nadie entiende es una negativa sin salida — por eso son las frases correctas para juzgar una traducción.",
  "webb.sprak.ej_granskad": "Sin revisar",
  "webb.sprak.granskad": "Revisado",
  "webb.sprak.granskad.text":
    "El texto de procedimiento en {sprak} ha sido leído por un especialista que ejerce el oficio. Los pasos y los puntos de control se muestran en {sprak} en todo momento.",
  "webb.sprak.val.etikett": "Operativa",
  "webb.sprak.val.rubrik": "Cómo se elige el idioma",
  "webb.sprak.val.s1.rubrik": "Preferencia del usuario",
  "webb.sprak.val.s1.text": "Lo que la persona ha seleccionado.",
  "webb.sprak.val.s2.rubrik": "Configuración de la organización",
  "webb.sprak.val.s2.text": "El idioma de documentación del taller.",
  "webb.sprak.val.s3.rubrik": "Idioma del navegador",
  "webb.sprak.val.s3.text": "El primer idioma que la plataforma reconoce.",
  "webb.sprak.val.s4.rubrik": "Inglés",
  "webb.sprak.val.s4.text": "El predeterminado, y la fuente.",
  "webb.sprak.val.notering":
    "La organización va deliberadamente por delante del navegador. Un taller en Alemania con un técnico polaco necesita un solo idioma de documentación — el expediente no debe cambiar de idioma según quién escribiera la línea.",

  // ---- Kunddelningen (ALVA-PROC-0030 · delningsvyn) -----------------------
  "sammanfattning.objekt": "El caso se refiere a {objekt}.",
  "sammanfattning.objekt_utan_namn": "El caso se refiere a un objeto identificado.",
  "sammanfattning.objekt_saknas": "El objeto no está identificado en el registro.",
  "sammanfattning.kundbeskrivning": "El cliente describió: «{text}»",
  "sammanfattning.repro.ja": "El síntoma se reprodujo.",
  "sammanfattning.repro.delvis": "El síntoma pudo reproducirse parcialmente.",
  "sammanfattning.repro.nej":
    "El síntoma no pudo reproducirse en las condiciones presentes durante el examen.",
  "sammanfattning.repro.dokumenterad": "La reproducción está documentada.",
  "sammanfattning.orsak_ej_faststalld": "La causa no pudo establecerse: {motivering}",
  "sammanfattning.avvikelse": "Anomalía constatada: {avvikelse}",
  "sammanfattning.bedomd_orsak": "Causa estimada: {kategori}.",
  "sammanfattning.motivering": "Justificación: {motivering}",
  "sammanfattning.atgard_utford": "Intervención realizada: {beskrivning}",
  "sammanfattning.atgard_ej_utford": "No se realizó ninguna intervención: {motivering}",
  "sammanfattning.kvalitet.symptomet_borta": "En el control de calidad el síntoma había desaparecido.",
  "sammanfattning.kvalitet.kvarstar": "En el control de calidad el síntoma persistía.",
  "sammanfattning.kvalitet.delvis": "En el control de calidad el síntoma persistía parcialmente.",
  "sammanfattning.kvalitet.ej_verifierbar": "El control de calidad no pudo verificar el resultado.",
  "sammanfattning.kvalitet.dokumenterad": "El control de calidad está documentado.",
  "sammanfattning.kvarstaende": "Pendiente: {text}",
  "sammanfattning.rad.oidentifierat": "Objeto no identificado",
  "sammanfattning.rad.pagaende": "{vad} — en curso.",
  "sammanfattning.rad.utan_orsak": "{vad} — cerrado sin causa establecida.",
  "sammanfattning.rad.avslutat": "{vad} — cerrado.",
  "delning.rubrik.fall": "Caso",
  "delning.rubrik.delat": "Caso compartido",
  "delning.status.avslutat": "Cerrado",
  "delning.status.pagaende": "Diagnóstico en curso",
  "delning.identitet.arbetsorder": "Orden de trabajo",
  "delning.identitet.claim": "Claim",
  "delning.identitet.skadenummer": "N.º de siniestro",
  "delning.identitet.regnr": "Matrícula",
  "delning.identitet.vin": "VIN",
  "delning.identitet.miltal": "Kilometraje",
  "delning.identitet.ansvarig": "Técnico responsable",
  "delning.identitet.status": "Estado",
  "delning.rubrik.sammanfattning": "Resumen",
  "delning.rubrik.slutsats": "Conclusión y justificación",
  "delning.slutsats.ej_faststalld": "Motivo por el que la causa no pudo establecerse",
  "delning.slutsats.motivering": "Justificación",
  "delning.slutsats.uteslutet": "Alternativas descartadas",
  "delning.slutsats.atgardsval": "Elección de la intervención",
  "delning.slutsats.kvarstaende": "Incertidumbre restante",
  "delning.rubrik.felbeskrivning": "Descripción de la avería por el cliente",
  "delning.rubrik.forslag": "Intervención propuesta",
  "delning.forslag.kostnad": "Coste estimado: {kostnad}",
  "delning.forslag.beslut": "Su decisión: {beslut}",
  "delning.forslag.via": "(registrada por {kanal})",
  "delning.forslag.vantar":
    "A la espera de su decisión — contacte con el taller para aprobar o rechazar.",
  "delning.beslut.rubrik": "Su decisión al taller",
  "delning.beslut.godkann": "Aprobar la intervención",
  "delning.beslut.avboj": "Rechazar",
  "delning.beslut.kommentar": "Comentario (opcional)",
  "delning.beslut.motivering": "Breve justificación (opcional)",
  "delning.beslut.skickar": "Enviando …",
  "delning.beslut.skicka": "Enviar la decisión",
  "delning.beslut.info":
    "La decisión queda registrada en el caso y no puede modificarse aquí — contacte con el taller si cambia de opinión.",
  "delning.beslut.godkant": "Aprobada",
  "delning.beslut.avbojt": "Rechazada",
  "delning.beslut.delvis": "Parcialmente aprobada",
  "delning.beslut.fel.plattform": "La decisión no puede darse aquí — contacte con el taller.",
  "delning.beslut.fel.registrering": "La decisión no pudo registrarse — inténtelo de nuevo.",
  "delning.beslut.fel.forbindelse": "La decisión no pudo enviarse — compruebe la conexión.",
  "delning.rubrik.laget": "Estado actual",
  "delning.rubrik.video": "Vídeo",
  "delning.rubrik.bilder": "Imágenes",
  "delning.rubrik.matningar": "Mediciones",
  "delning.rubrik.tidslinje": "Cronología",
  "delning.tidslinje.arbetssprak": "Las entradas se muestran literalmente, en el idioma de trabajo del taller.",
  "delning.rubrik.nasta": "Próximo paso recomendado",
  "delning.rubrik.arbetstid": "Tiempo de trabajo",
  "delning.fot": "Caso #{nummer} · iniciado {datum} · generado a partir del registro del caso",
  "delning.notis.kund":
    "Vista en directo de solo lectura desde el taller — la página se actualiza automáticamente a medida que se registra nueva información.",
  "delning.notis.partner":
    "Vista en directo de solo lectura (nivel socio) — incluye hipótesis técnicas, claramente marcadas como no verificadas. Se actualiza automáticamente.",
  "delning.notis.intern":
    "Vista en directo de solo lectura (nivel interno) — visibilidad completa del caso. Se actualiza automáticamente.",
  "delning.hamtar": "Recuperando el caso …",
  "delning.saknas": "El caso no está disponible. Verifique el enlace con el taller — el acceso compartido puede haberse revocado.",
};
