// ALVA-SPEC-060 · Français.
//
// Les instructions sont à l’infinitif, sans s’adresser à l’utilisateur :
// « Photographier le compteur », et non « Photographiez le compteur ».
// C’est le registre des consignes techniques, et cela respecte
// ALVA-SPEC-001 §7 — le système signale un état, il ne s’adresse pas à
// l’opérateur.
//
// `granskat: false` : l’interface est traduite, le texte de procédure
// n’est pas relu par un spécialiste. Voir index.mjs.

export const FR = {
  // ---- Degrés de preuve ---------------------------------------------------
  "evidens.E1": "Observation",
  "evidens.E2": "Photographie",
  "evidens.E3": "Vidéo avec son",
  "evidens.E4": "Mesure, instrument étalonné",
  "evidens.E5": "Document",
  "evidens.ej_kalibrerad": "étalonnage manquant ou expiré",
  "evidens.ej_angivet": "instrument non indiqué",
  "evidens.ej_fotograferad": "saisi, non photographié",

  // ---- Le contrôle de clôture ---------------------------------------------
  "grind.objekt": "Identification du véhicule ou de l’objet vérifiée",
  "grind.historik": "Historique du véhicule vérifié, ou son omission justifiée",
  "grind.historik.nekad": "Un contrôle d’historique refusé exige que le motif soit indiqué.",
  "grind.historik.saknas": "Aucun contrôle d’historique documenté.",
  "grind.matarstallning.ingaende": "Kilométrage à la réception photographié",
  "grind.matarstallning.utgaende": "Kilométrage à la restitution photographié",
  "grind.matarstallning.saknas": "Aucun kilométrage documenté.",
  "grind.matarstallning.ej_foto":
    "Le kilométrage est saisi mais non photographié. Photographier le compteur, ou indiquer pourquoi cela n’est pas possible.",
  "grind.reproducering": "Vérification du symptôme : reproduit, ou documenté comme non reproductible",
  "grind.felorsak": "Analyse de la cause racine documentée",
  "grind.atgard": "Action corrective documentée, ou son absence justifiée",
  "grind.atgard.saknas": "Ni action réalisée ni motif de son absence n’est documenté.",
  "grind.kundbeslut": "Décision du client sur la proposition enregistrée",
  "grind.kundbeslut.avbojt": "Travaux réalisés malgré une proposition refusée",
  "grind.kundbeslut.avbojt.detalj":
    "Le client a refusé la proposition, mais des travaux sont documentés comme réalisés.",
  "grind.kvalitetskontroll": "Contrôle qualité effectué — symptôme vérifié comme résolu",
  "grind.kontroller": "Points de contrôle de la méthode : preuve, ou dérogation documentée",
  "grind.foton": "Photographies présentes pour les points de contrôle qui les exigent",
  "grind.slutsats": "Conclusion (ALVA-RULE-200)",
  "grind.hogvolt.behorighet": "Habilitation haute tension confirmée",
  "grind.hogvolt.spanningslos": "Véhicule consigné hors tension selon la procédure du constructeur, absence de tension vérifiée par mesure",
  "grind.regelpaket": "La signature du paquet de règles ne correspond pas — clôture bloquée.",
  "grind.regelpaket.osignerat": "Un paquet de règles externe est utilisé sans signature — clôture bloquée.",
  "grind.evidens": "Niveau de preuve supérieur à E0",
  "grind.evidens.saknas": "Aucune preuve d’aucune sorte ne figure dans le journal.",
  "grind.foton.detalj": "{kontroller} points de contrôle exigent une photographie, {foton} photographies dans le journal.",
  "grind.sparr.ej_uppfyllt": "L’exigence de sécurité n’est pas satisfaite.",
  "grind.sparr.kringgangen": "Une condition de sécurité a été renseignée et non satisfaite. Elle ne peut pas être écartée en changeant de méthodologie — satisfaites-la, ou si la méthodologie était erronée, la question de sécurité n'aurait pas dû y être renseignée.",
  "grind.arendetyp.okant": "Exigence inconnue dans le paquet de règles : {krav}",
  "grind.arendetyp.krav": "Exigence pour ce type de dossier : {krav}",
  "grind.sakerhet": "Niveau de confiance dans les limites de ce que les preuves soutiennent",
  "grind.sakerhet.detalj": "La confiance indiquée ({niva}) dépasse ce que les preuves soutiennent ({tak}). Compléter les preuves, ou abaisser le niveau — une incertitude honnête est une information.",
  "grind.eskalering": "Escalades techniques traitées",
  "grind.eskalering.detalj": "Une escalade est ouverte ({referens}). Attendre la réponse et la documenter avant de clôturer le dossier.",


  // ---- La conclusion (ALVA-RULE-200) --------------------------------------
  "slutsats.rubrik": "Conclusion",
  "slutsats.konstaterat": "Ce qui est établi",
  "slutsats.evidens": "Quelles preuves l’étayent",
  "slutsats.avfardat": "Quelles hypothèses ont été écartées, et pourquoi",
  "slutsats.osakert": "Ce qui reste incertain",
  "slutsats.ickesvar": "Ce n’est pas une réponse. Indiquer ce qui est établi et quelles preuves l’étayent.",
  "slutsats.falt.motivering": "Justification",
  "slutsats.falt.motivering_ej": "Motif pour lequel la cause n’a pas pu être établie",
  "slutsats.falt.uteslutet": "Alternatives écartées",
  "slutsats.falt.kvarstaende": "Incertitude restante",
  "slutsats.falt.atgardsval": "Choix de l’action",
  "slutsats.saknas": "Le champ « {falt} » est absent.",
  "slutsats.ickesvar.falt": "{falt} : « {text} » n’est pas un motif. Indiquer ce qui s’applique réellement, et pourquoi.",
  "slutsats.for_kort": "Le champ « {falt} » est trop court ({langd} caractères sur un minimum de {minsta}) pour être vérifiable après coup.",
  "slutsats.utan_varfor": "{falt} indique le quoi, mais pas le pourquoi. Relier la conclusion aux preuves — qu’est-ce qui, dans celles-ci, la rend fondée ?",
  "slutsats.utan_slutsats": "Le dossier ne peut pas être clôturé sans conclusion. Indiquer pourquoi la conclusion découle des preuves.",
  "slutsats.hypotes_obemott": "L’hypothèse « {text} » figure dans le journal mais n’est pas traitée. Indiquer pourquoi elle a été écartée, ou pourquoi elle reste ouverte.",


  // ---- Flux du dossier ----------------------------------------------------
  "arende.nytt": "Nouveau dossier",
  "arende.oppna": "Dossiers ouverts",
  "arende.avslutade": "Dossiers clôturés",
  "arende.avsluta": "Clôturer le dossier",
  "arende.avslutat": "Dossier clôturé",
  "arende.kan_ej_avslutas": "Le dossier ne peut pas encore être clôturé",
  "arende.hinder": "En suspens avant clôture",
  "arende.overlamna": "Transmettre",
  "arende.ansvarig": "Responsable",

  // ---- Contrôle préalable -------------------------------------------------
  "pre.rubrik": "Contrôle préalable — avant le début des travaux",
  "pre.historik.fraga":
    "L’historique du véhicule a-t-il été vérifié ? (travaux antérieurs, défauts récurrents, TSB, campagnes)",
  "pre.historik.ja": "Oui — vérifié",
  "pre.historik.nej": "Non",
  "pre.historik.skal": "Motif pour lequel l’historique n’a pas été vérifié (obligatoire)",
  "pre.historik.relevant": "Travaux antérieurs pertinents (facultatif — chaîne causale)",
  "pre.matarstallning": "Kilométrage",
  "pre.fotografera": "Photographier le tableau de bord",
  "pre.felbeskrivning": "Description du défaut par le client vérifiée",
  "pre.observationer": "Autre chose à la réception ?",

  // ---- Actions ------------------------------------------------------------
  "handling.spara": "Enregistrer",
  "handling.avbryt": "Annuler",
  "handling.fortsatt": "Continuer",
  "handling.tillbaka": "Retour",
  "handling.dokumentera": "Documenter",
  "handling.fotografera": "Photographier",
  "handling.spela_in": "Enregistrer une vidéo",
  "handling.undantag": "Documenter une dérogation",
  "handling.undantag.skal": "Motif de la dérogation (obligatoire)",
  "handling.exportera": "Exporter",
  "handling.skriv_ut": "Imprimer",

  // ---- Mesure -------------------------------------------------------------
  "matning.varde": "Valeur",
  "matning.enhet": "Unité",
  "matning.matdon": "Instrument",
  "matning.matdon.valj": "Sélectionner un instrument",
  "matning.matdon.okant": "Instrument inconnu. Le déclarer avant d’enregistrer la mesure.",
  "matning.kalibrerad_till": "Étalonné jusqu’au",

  // ---- Rapport ------------------------------------------------------------
  "rapport.rubrik": "Rapport de dossier",
  "rapport.sammanfattning": "Synthèse",
  "rapport.evidens": "Preuves",
  "rapport.atgarder": "Actions",
  "rapport.harledd":
    "Généré à partir du journal du dossier. Les observations et les mesures sont rapportées sans conclusions dépourvues de fondement.",

  // ---- Langue -------------------------------------------------------------
  "sprak.valj": "Langue",
  "sprak.granskat": "Relu",
  "sprak.ogranskat": "Non relu",
  "sprak.tackning": "{procent} % de l’interface",

  "metodik.ogranskad":
    "Le texte de procédure n’a pas été relu par un spécialiste technique en {sprak}. Les étapes et les points de contrôle sont affichés en anglais lorsqu’aucune traduction relue n’existe — une traduction non relue d’une consigne de sécurité est pire qu’une consigne en langue étrangère, parce qu’elle n’a pas l’air étrangère.",
  "metodik.pa_engelska": "Affiché en anglais — aucune traduction relue en {sprak}",

  // ---- Site public (webb.) -----------------------------------------------
  "webb.nav.oversikt": "Aperçu",
  "webb.ansok": "Demander un compte",
  "webb.loggain": "Connexion",
  "webb.fot.impressum": "Mentions légales",
  "webb.fot.dataskydd": "Confidentialité",
  "webb.fot.villkor": "Conditions",
  "webb.fot.tillganglighet": "Accessibilité",
  "webb.fot.sprak": "Langues",
  "webb.fot.utgavor": "Notes de version",

  "webb.hero.position": "Plateforme de diagnostic guidé",
  "webb.hero.definition": "Des procédures de diagnostic normalisées pour une recherche de pannes répétable et vérifiable.",

  "webb.metod.etikett": "Méthodologie",
  "webb.metod.rubrik": "Le modèle ALVA",
  "webb.metod.ingress":
    "ALVA est une méthode normalisée d’analyse, de localisation, de vérification et d’action systématiques. Chaque décision est traçable, chaque conclusion vérifiable, chaque action reproductible.",
  "webb.fas.analysis.syfte": "Recueillir les preuves.",
  "webb.fas.analysis.avgransning": "Des faits uniquement. Les hypothèses ne sont pas recueillies dans cette phase.",
  "webb.fas.localization.syfte": "Circonscrire le défaut.",
  "webb.fas.localization.avgransning": "Restreindre la zone. La cause n’est pas encore établie.",
  "webb.fas.verification.syfte": "Confirmer la cause racine.",
  "webb.fas.verification.avgransning": "C’est la cause qui est vérifiée — pas le symptôme.",
  "webb.fas.action.syfte": "Exécuter l’action corrective.",
  "webb.fas.action.avgransning": "Résultat vérifié et documenté. Sinon la phase est incomplète.",

  "webb.drift.etikett": "Fonctionnement",
  "webb.drift.rubrik": "Comment ça fonctionne",
  "webb.drift.s1.rubrik": "Créer l’organisation",
  "webb.drift.s1.text": "L’inscription est soumise puis examinée.",
  "webb.drift.s2.rubrik": "Les utilisateurs reçoivent leurs comptes",
  "webb.drift.s2.text": "Les rôles sont attribués par l’administrateur de l’organisation.",
  "webb.drift.s3.rubrik": "Procédures de diagnostic guidées",
  "webb.drift.s3.text": "Chaque dossier suit une procédure définie.",
  "webb.drift.s4.rubrik": "Vérification",
  "webb.drift.s4.text": "La cause racine est confirmée avant l’action corrective.",
  "webb.drift.s5.rubrik": "Documentation",
  "webb.drift.s5.text": "Le rapport est généré à partir du journal du dossier.",
  "webb.drift.s6.rubrik": "Amélioration continue",
  "webb.drift.s6.text": "Les résultats vérifiés affinent les procédures suivantes.",

  "webb.larande.etikett": "Capacité",
  "webb.larande.rubrik": "Apprentissage de l’organisation",
  "webb.larande.p1":
    "La plateforme affine en continu les procédures de diagnostic à partir de l’expérience opérationnelle vérifiée de votre propre organisation.",
  "webb.larande.p2":
    "Chaque diagnostic achevé nourrit le guidage suivant. Seuls les résultats vérifiés sont utilisés — un dossier clôturé sans cause racine confirmée n’apporte rien, à dessein.",
  "webb.larande.p3":
    "La base de connaissances appartient à l’organisation. Elle est dérivée de vos dossiers, de vos procédures et de votre documentation, et elle n’est pas agrégée entre clients.",
  "webb.larande.block": "Dérivée de",
  "webb.larande.k1": "Causes racines vérifiées",
  "webb.larande.k2": "Actions correctives confirmées",
  "webb.larande.k3": "Catégories de défauts récurrents",
  "webb.larande.k4": "Procédures menées à terme",
  "webb.larande.k5": "Documentation de l’organisation",

  "webb.rapport.etikett": "Rapports",
  "webb.rapport.rubrik": "Rapport trimestriel d’amélioration",
  "webb.rapport.ingress":
    "Une fois par trimestre, la plateforme répond à six questions sur le travail de l’atelier lui-même. Chaque réponse est dérivée du journal des dossiers — rien n’est estimé, et rien n’est demandé à personne.",
  "webb.rapport.f1": "Quels défauts diagnostiquons-nous désormais correctement du premier coup ?",
  "webb.rapport.f2": "À quelle fréquence une cause soupçonnée se révèle-t-elle être la vraie ?",
  "webb.rapport.f3": "Quels défauts reviennent sans cesse dans le parc ?",
  "webb.rapport.f4": "Quelles étapes de procédure sont sautées, et pourquoi ?",
  "webb.rapport.f5": "Que sait l’atelier aujourd’hui qu’il ne savait pas au trimestre dernier ?",
  "webb.rapport.f6": "Les dossiers sont-ils clôturés, vérifiés et documentés — ou seulement clôturés ?",

  "webb.pris.etikett": "Commercial",
  "webb.pris.rubrik": "Licences",
  "webb.pris.komponent": "Composant",
  "webb.pris.grund": "Base",
  "webb.pris.plattform": "Licence de plateforme",
  "webb.pris.plattform.grund": "Par organisation, annuelle",
  "webb.pris.anvandare": "Licences utilisateur",
  "webb.pris.anvandare.grund": "Par utilisateur actif, mensuelle",
  "webb.pris.moduler": "Modules d’entreprise",
  "webb.pris.moduler.grund": "Optionnels, par module",
  "webb.pris.betalning": "Aucun paiement en ligne. Aucune souscription d’abonnement. La facturation suit l’examen de la demande.",
  "webb.pris.aktivering": "Séquence d’activation",
  "webb.pris.a1": "L’organisation soumet son inscription.",
  "webb.pris.a2": "La demande est examinée.",
  "webb.pris.a3": "La facture est émise.",
  "webb.pris.a4": "Le paiement est enregistré.",
  "webb.pris.a5": "L’organisation est activée.",
  "webb.pris.a6": "Les utilisateurs supplémentaires sont facturés mensuellement.",

  "webb.kallor.etikett": "Infrastructure",
  "webb.kallor.rubrik": "Infrastructure de connaissances opérationnelles",
  "webb.kallor.p1":
    "ALVA utilise les sources de connaissances autorisées propres à l’organisation. L’architecture est neutre vis-à-vis des fournisseurs : chaque source implémente la même interface, et aucun fournisseur n’est présupposé.",
  "webb.kallor.p2":
    "Une installation bêta fonctionne sur la seule documentation interne. Les fournisseurs externes sont activés plus tard par des connecteurs séparés, sans modification du cœur de la plateforme.",
  "webb.kallor.block": "Ordre de résolution des sources",
  "webb.kallor.k1": "Procédures internes de l’entreprise",
  "webb.kallor.k2": "Documentation OEM",
  "webb.kallor.k3": "Bulletins techniques",
  "webb.kallor.k4": "Informations de garantie",
  "webb.kallor.k5": "Manuels d’atelier",
  "webb.kallor.k6": "Diagnostics vérifiés historiques",
  "webb.kallor.k7": "Bonnes pratiques de l’organisation",

  "webb.login.etikett": "Accès",
  "webb.login.demo":
    "Cette connexion n’authentifie rien. Saisissez n’importe quoi dans E-mail et Mot de passe et appuyez sur Se connecter — aucun compte n’est nécessaire, et le portail derrière présente des données d’exemple figées. Reliée à une instance de la plateforme, cette page s’authentifie auprès d’elle, et le portail est fermé sans session valide.",
  "webb.login.losenord": "Mot de passe",
  "webb.login.ofullstandigt": "Authentification incomplète. E-mail et mot de passe requis.",
  "webb.login.misslyckades": "Échec de l’authentification.",
  "webb.login.logga_in": "Se connecter",
  "webb.login.loggar_in": "Connexion en cours",
  "webb.login.glomt": "Mot de passe oublié",

  "webb.ansokan.etikett": "Inscription",
  "webb.ansokan.demo":
    "Rien n’est envoyé. Soumettre ce formulaire n’enregistre rien, ne notifie personne et ne crée aucune demande — aucun traitement n’existe encore derrière. La description ci-dessous indique comment l’inscription est censée fonctionner, pas ce qui se passe aujourd’hui.",
  "webb.ansokan.avsikt": "Fonctionnement prévu : les demandes sont examinées manuellement et aucun paiement n’est perçu à ce stade.",
  "webb.falt.foretag": "Entreprise",
  "webb.falt.orgnummer": "Numéro d’immatriculation de l’entreprise",
  "webb.falt.kontakt": "Personne à contacter",
  "webb.falt.epost": "E-mail",
  "webb.falt.telefon": "Téléphone",
  "webb.falt.tekniker": "Nombre de techniciens",
  "webb.falt.bransch": "Secteur",
  "webb.falt.land": "Pays",
  "webb.falt.anvandare": "Nombre d’utilisateurs attendu",
  "webb.falt.noteringar": "Remarques",
  "webb.falt.kravs": "(obligatoire)",
  "webb.ansokan.skicka": "Soumettre la demande",
  "webb.ansokan.mottagen.etikett": "Demande",
  "webb.ansokan.mottagen": "Soumise",
  "webb.ansokan.mottagen.demo":
    "Rien n’a été transmis et personne n’a été notifié. La référence ci-dessous a été calculée dans votre navigateur à partir de votre saisie et n’existe nulle part ailleurs — elle disparaîtra à la fermeture de cette page.",
  "webb.ansokan.status": "Statut",
  "webb.ansokan.referens": "Référence",
  "webb.ansokan.granskning":
    "Les demandes sont examinées manuellement. Une facture est émise à l’approbation. L’organisation est activée une fois le paiement enregistré.",

  "webb.sprak.etikett": "Localisation",
  "webb.sprak.rubrik": "Langues",
  "webb.sprak.ingress":
    "L’anglais est la langue par défaut et la langue source. Neuf traductions suivent. Ce que la plateforme ne fait pas : prétendre qu’une interface traduite signifie une méthode traduite.",
  "webb.sprak.princip.etikett": "Principe",
  "webb.sprak.princip.rubrik": "Deux sortes de texte",
  "webb.sprak.granssnitt.rubrik": "Texte d’interface",
  "webb.sprak.granssnitt.beteckning": "Retombe silencieusement",
  "webb.sprak.granssnitt.text":
    "Étiquettes, boutons, statuts. Fini, rarement modifié. Une chaîne anglaise qui atteint un utilisateur allemand est un agacement, pas un danger — une traduction manquante retombe donc sur l’anglais sans commentaire.",
  "webb.sprak.metodik.rubrik": "Texte de procédure",
  "webb.sprak.metodik.beteckning": "Ne retombe jamais silencieusement",
  "webb.sprak.metodik.text":
    "Des instructions pour travailler sur un véhicule. Ici, une traduction non relue est pire qu’une version en langue étrangère — parce que l’anglais a l’air étranger, tandis qu’une mauvaise traduction a l’air d’une instruction. Elle est affichée en anglais et signalée, avec la langue nommée.",
  "webb.sprak.invariant":
    "La méthode elle-même n’est jamais traduite. Les noms de phase et les mots de statut sont la structure d’ALVA et se lisent à l’identique dans chaque pays, si bien qu’un auditeur peut lire un dossier roumain et un dossier allemand sans savoir dans quelle langue l’atelier travaille.",
  "webb.sprak.tackning.etikett": "Couverture",
  "webb.sprak.tackning.rubrik": "Ce qui est traduit, et ce qui est relu",
  "webb.sprak.kolumn.sprak": "Langue",
  "webb.sprak.kolumn.granssnitt": "Interface",
  "webb.sprak.kolumn.granskat": "Méthode relue par un spécialiste",
  "webb.sprak.granskat.ja": "Oui",
  "webb.sprak.granskat.nej": "Non — texte de procédure affiché en anglais",
  "webb.sprak.matt":
    "La couverture de l’interface est mesurée, pas estimée : un test fait échouer la compilation si une clé manque dans une langue. Le statut de relecture est une affirmation sur des personnes, pas sur des fichiers, et il est fixé à la main.",
  "webb.sprak.kallsprak":
    "Le texte de procédure anglais est une traduction de la source suédoise et n’a pas encore été lu par un spécialiste exerçant le métier. Il est tenu au même niveau d’exigence que les neuf autres langues, et la même déclaration est faite ici à son sujet au lieu de l’excepter discrètement parce qu’il est la source.",
  "webb.sprak.bevis.etikett": "Vérification",
  "webb.sprak.bevis.rubrik": "Les phrases qui arrêtent un dossier",
  "webb.sprak.bevis.ingress":
    "Ce sont les phrases qui empêchent un technicien de clôturer un dossier. Un refus que personne ne comprend est un refus sans issue — ce sont donc les bonnes phrases pour juger une traduction.",
  "webb.sprak.ej_granskad": "Non relu",
  "webb.sprak.granskad": "Relu",
  "webb.sprak.granskad.text":
    "Le texte de procédure en {sprak} a été lu par un spécialiste exerçant le métier. Les étapes et les points de contrôle sont affichés en {sprak} partout.",
  "webb.sprak.val.etikett": "Fonctionnement",
  "webb.sprak.val.rubrik": "Comment la langue est choisie",
  "webb.sprak.val.s1.rubrik": "Préférence de l’utilisateur",
  "webb.sprak.val.s1.text": "Ce que la personne a choisi.",
  "webb.sprak.val.s2.rubrik": "Réglage de l’organisation",
  "webb.sprak.val.s2.text": "La langue de documentation de l’atelier.",
  "webb.sprak.val.s3.rubrik": "Langue du navigateur",
  "webb.sprak.val.s3.text": "La première langue que la plateforme reconnaît.",
  "webb.sprak.val.s4.rubrik": "Anglais",
  "webb.sprak.val.s4.text": "La langue par défaut, et la source.",
  "webb.sprak.val.notering":
    "L’organisation passe délibérément avant le navigateur. Un atelier en Allemagne avec un technicien polonais a besoin d’une seule langue de documentation — le dossier ne doit pas changer de langue selon qui a écrit la ligne.",

  // ---- Kunddelningen (ALVA-PROC-0030 · delningsvyn) -----------------------
  "sammanfattning.objekt": "Le dossier concerne {objekt}.",
  "sammanfattning.objekt_utan_namn": "Le dossier concerne un objet identifié.",
  "sammanfattning.objekt_saknas": "L’objet n’est pas identifié dans le journal.",
  "sammanfattning.kundbeskrivning": "Le client a décrit : « {text} »",
  "sammanfattning.repro.ja": "Le symptôme a été reproduit.",
  "sammanfattning.repro.delvis": "Le symptôme a pu être partiellement reproduit.",
  "sammanfattning.repro.nej":
    "Le symptôme n’a pas pu être reproduit dans les conditions présentes lors de l’examen.",
  "sammanfattning.repro.dokumenterad": "La reproduction est documentée.",
  "sammanfattning.orsak_ej_faststalld": "La cause n’a pas pu être établie : {motivering}",
  "sammanfattning.avvikelse": "Anomalie constatée : {avvikelse}",
  "sammanfattning.bedomd_orsak": "Cause estimée : {kategori}.",
  "sammanfattning.motivering": "Justification : {motivering}",
  "sammanfattning.atgard_utford": "Intervention effectuée : {beskrivning}",
  "sammanfattning.atgard_ej_utford": "Aucune intervention effectuée : {motivering}",
  "sammanfattning.kvalitet.symptomet_borta": "Au contrôle qualité, le symptôme avait disparu.",
  "sammanfattning.kvalitet.kvarstar": "Au contrôle qualité, le symptôme persistait.",
  "sammanfattning.kvalitet.delvis": "Au contrôle qualité, le symptôme persistait partiellement.",
  "sammanfattning.kvalitet.ej_verifierbar": "Le contrôle qualité n’a pas pu vérifier le résultat.",
  "sammanfattning.kvalitet.dokumenterad": "Le contrôle qualité est documenté.",
  "sammanfattning.kvarstaende": "Reste à traiter : {text}",
  "sammanfattning.rad.oidentifierat": "Objet non identifié",
  "sammanfattning.rad.pagaende": "{vad} — en cours.",
  "sammanfattning.rad.utan_orsak": "{vad} — clôturé sans cause établie.",
  "sammanfattning.rad.avslutat": "{vad} — clôturé.",
  "delning.rubrik.fall": "Dossier",
  "delning.rubrik.delat": "Dossier partagé",
  "delning.status.avslutat": "Clôturé",
  "delning.status.pagaende": "Diagnostic en cours",
  "delning.identitet.arbetsorder": "Ordre de réparation",
  "delning.identitet.claim": "Claim",
  "delning.identitet.skadenummer": "N° de sinistre",
  "delning.identitet.regnr": "Immatriculation",
  "delning.identitet.vin": "VIN",
  "delning.identitet.miltal": "Kilométrage",
  "delning.identitet.ansvarig": "Technicien responsable",
  "delning.identitet.status": "Statut",
  "delning.rubrik.sammanfattning": "Synthèse",
  "delning.rubrik.slutsats": "Conclusion et justification",
  "delning.slutsats.ej_faststalld": "Raison pour laquelle la cause n’a pas pu être établie",
  "delning.slutsats.motivering": "Justification",
  "delning.slutsats.uteslutet": "Alternatives écartées",
  "delning.slutsats.atgardsval": "Choix de l’intervention",
  "delning.slutsats.kvarstaende": "Incertitude restante",
  "delning.rubrik.felbeskrivning": "Description du défaut par le client",
  "delning.rubrik.forslag": "Intervention proposée",
  "delning.forslag.kostnad": "Coût estimé : {kostnad}",
  "delning.forslag.beslut": "Votre décision : {beslut}",
  "delning.forslag.via": "(enregistrée via {kanal})",
  "delning.forslag.vantar":
    "Dans l’attente de votre décision — contactez l’atelier pour approuver ou refuser.",
  "delning.beslut.rubrik": "Votre décision à l’atelier",
  "delning.beslut.godkann": "Approuver l’intervention",
  "delning.beslut.avboj": "Refuser",
  "delning.beslut.kommentar": "Commentaire (facultatif)",
  "delning.beslut.motivering": "Brève justification (facultative)",
  "delning.beslut.skickar": "Envoi …",
  "delning.beslut.skicka": "Envoyer la décision",
  "delning.beslut.info":
    "La décision est consignée dans le dossier et ne peut pas être modifiée ici — contactez l’atelier si vous changez d’avis.",
  "delning.beslut.godkant": "Approuvée",
  "delning.beslut.avbojt": "Refusée",
  "delning.beslut.delvis": "Partiellement approuvée",
  "delning.beslut.fel.plattform": "La décision ne peut pas être donnée ici — contactez l’atelier.",
  "delning.beslut.fel.registrering": "La décision n’a pas pu être enregistrée — réessayez.",
  "delning.beslut.fel.forbindelse": "La décision n’a pas pu être envoyée — vérifiez la connexion.",
  "delning.rubrik.laget": "État actuel",
  "delning.rubrik.video": "Vidéo",
  "delning.rubrik.bilder": "Photos",
  "delning.rubrik.matningar": "Mesures",
  "delning.rubrik.tidslinje": "Chronologie",
  "delning.tidslinje.arbetssprak": "Les entrées sont restituées mot pour mot, dans la langue de travail de l’atelier.",
  "delning.rubrik.nasta": "Prochaine étape recommandée",
  "delning.rubrik.arbetstid": "Temps de travail",
  "delning.fot": "Dossier #{nummer} · ouvert le {datum} · généré à partir du journal du dossier",
  "delning.notis.kund":
    "Vue en direct en lecture seule depuis l’atelier — la page se met à jour automatiquement à mesure que de nouvelles informations sont consignées.",
  "delning.notis.partner":
    "Vue en direct en lecture seule (niveau partenaire) — inclut des hypothèses techniques, clairement signalées comme non vérifiées. Mise à jour automatique.",
  "delning.notis.intern":
    "Vue en direct en lecture seule (niveau interne) — visibilité complète du dossier. Mise à jour automatique.",
  "delning.hamtar": "Récupération du dossier …",
  "delning.saknas": "Le dossier n’est pas disponible. Vérifiez le lien avec l’atelier — le partage a peut-être été révoqué.",
};
