// ALVA-SPEC-060 · Português.
//
// Português europeu (pt-PT), sem o Acordo aplicado às formas em que as
// duas normas divergem de maneira visível para um técnico: «contacto»,
// «registo», «conta-quilómetros». Se surgir um mercado brasileiro, é uma
// entrada nova no catálogo — «pt-BR» — e não uma emenda a esta.
//
// `granskat: false`: a interface está traduzida, o texto dos
// procedimentos não foi revisto por um especialista. Ver index.mjs.

export const PT = {
  // ---- Graus de evidência -------------------------------------------------
  "evidens.E1": "Observação",
  "evidens.E2": "Fotografia",
  "evidens.E3": "Vídeo com som",
  "evidens.E4": "Medição, instrumento calibrado",
  "evidens.E5": "Documento",
  "evidens.ej_kalibrerad": "calibração em falta ou expirada",
  "evidens.ej_angivet": "instrumento não indicado",
  "evidens.ej_fotograferad": "introduzido, não fotografado",

  // ---- O controlo de encerramento -----------------------------------------
  "grind.objekt": "Identificação do veículo ou do objeto verificada",
  "grind.historik": "Histórico do veículo verificado, ou a omissão da verificação justificada",
  "grind.historik.nekad": "Uma verificação de histórico recusada exige a indicação de um motivo.",
  "grind.historik.saknas": "Nenhuma verificação de histórico documentada.",
  "grind.matarstallning.ingaende": "Quilometragem à entrada fotografada",
  "grind.matarstallning.utgaende": "Quilometragem à saída fotografada",
  "grind.matarstallning.saknas": "Nenhuma quilometragem documentada.",
  "grind.matarstallning.ej_foto":
    "A quilometragem está introduzida mas não fotografada. Fotografar o conta-quilómetros, ou indicar por que motivo não é possível.",
  "grind.reproducering": "Verificação do sintoma: reproduzido, ou documentado como não reproduzível",
  "grind.felorsak": "Análise da causa raiz documentada",
  "grind.atgard": "Ação corretiva documentada, ou a sua ausência justificada",
  "grind.atgard.saknas": "Não está documentada nem uma ação realizada nem um motivo para a sua ausência.",
  "grind.kundbeslut": "Decisão do cliente sobre a proposta registada",
  "grind.kundbeslut.avbojt": "Trabalho realizado apesar de uma proposta recusada",
  "grind.kundbeslut.avbojt.detalj": "O cliente recusou a proposta, mas há trabalho documentado como realizado.",
  "grind.kvalitetskontroll": "Controlo de qualidade efetuado — sintoma verificado como resolvido",
  "grind.kontroller": "Pontos de controlo da metodologia: evidência, ou uma exceção documentada",
  "grind.foton": "Fotografias presentes nos pontos de controlo que as exigem",
  "grind.slutsats": "Conclusão (ALVA-RULE-200)",
  "grind.hogvolt.behorighet": "Habilitação de alta tensão confirmada",
  "grind.hogvolt.spanningslos": "Veículo colocado fora de tensão segundo o procedimento do fabricante, ausência de tensão verificada por medição",
  "grind.regelpaket": "A assinatura do pacote de regras não corresponde — encerramento bloqueado.",
  "grind.regelpaket.osignerat":
    "Está a ser utilizado um pacote de regras externo sem assinatura — encerramento bloqueado.",
  "grind.evidens": "Nível de evidência superior a E0",
  "grind.evidens.saknas": "Não existe qualquer evidência no registo.",
  "grind.foton.detalj": "{kontroller} pontos de controlo exigem fotografia, {foton} fotografias no registo.",
  "grind.sparr.ej_uppfyllt": "O requisito de segurança não está cumprido.",
  "grind.arendetyp.okant": "Requisito desconhecido no pacote de regras: {krav}",
  "grind.arendetyp.krav": "Requisito para este tipo de processo: {krav}",
  "grind.sakerhet": "Nível de confiança dentro do que a evidência sustenta",
  "grind.sakerhet.detalj": "A confiança indicada ({niva}) excede o que a evidência sustenta ({tak}). Completar a evidência, ou baixar o nível — a incerteza honesta é informação.",
  "grind.eskalering": "Escalonamentos técnicos respondidos",
  "grind.eskalering.detalj": "Há um escalonamento em aberto ({referens}). Aguardar a resposta e documentá-la antes de encerrar o processo.",


  // ---- A conclusão (ALVA-RULE-200) ----------------------------------------
  "slutsats.rubrik": "Conclusão",
  "slutsats.konstaterat": "O que foi estabelecido",
  "slutsats.evidens": "Que evidência o sustenta",
  "slutsats.avfardat": "Que hipóteses foram afastadas, e porquê",
  "slutsats.osakert": "O que permanece incerto",
  "slutsats.ickesvar": "Isso não é uma conclusão. Indicar o que foi estabelecido e que evidência o sustenta.",
  "slutsats.falt.motivering": "Fundamentação",
  "slutsats.falt.motivering_ej": "Motivo pelo qual a causa não pôde ser estabelecida",
  "slutsats.falt.uteslutet": "Alternativas afastadas",
  "slutsats.falt.kvarstaende": "Incerteza remanescente",
  "slutsats.falt.atgardsval": "Escolha da ação",
  "slutsats.saknas": "Falta o campo «{falt}».",
  "slutsats.ickesvar.falt": "{falt}: «{text}» não é uma fundamentação. Indicar o que se aplica realmente, e porquê.",
  "slutsats.for_kort": "O campo «{falt}» é demasiado curto ({langd} de pelo menos {minsta} caracteres) para poder ser verificado posteriormente.",
  "slutsats.utan_varfor": "{falt} indica o quê, mas não o porquê. Ligar a conclusão à evidência — o que nela faz com que isto decorra?",
  "slutsats.utan_slutsats": "O processo não pode ser encerrado sem uma conclusão. Indicar por que motivo a conclusão decorre da evidência.",
  "slutsats.hypotes_obemott": "A hipótese «{text}» consta do registo mas não é tratada. Indicar por que motivo foi afastada, ou por que motivo permanece em aberto.",


  // ---- Fluxo do processo --------------------------------------------------
  "arende.nytt": "Novo processo",
  "arende.oppna": "Processos abertos",
  "arende.avslutade": "Processos encerrados",
  "arende.avsluta": "Encerrar o processo",
  "arende.avslutat": "Processo encerrado",
  "arende.kan_ej_avslutas": "O processo ainda não pode ser encerrado",
  "arende.hinder": "Pendente antes do encerramento",
  "arende.overlamna": "Transferir",
  "arende.ansvarig": "Responsável",

  // ---- Verificação prévia -------------------------------------------------
  "pre.rubrik": "Verificação prévia — antes do início do trabalho",
  "pre.historik.fraga":
    "O histórico do veículo foi verificado? (trabalhos anteriores, avarias recorrentes, TSB, campanhas)",
  "pre.historik.ja": "Sim — verificado",
  "pre.historik.nej": "Não",
  "pre.historik.skal": "Motivo pelo qual o histórico não foi verificado (obrigatório)",
  "pre.historik.relevant": "Trabalhos anteriores relevantes (opcional — cadeia causal)",
  "pre.matarstallning": "Quilometragem",
  "pre.fotografera": "Fotografar o painel de instrumentos",
  "pre.felbeskrivning": "Descrição da avaria pelo cliente verificada",
  "pre.observationer": "Mais alguma coisa na receção?",

  // ---- Ações --------------------------------------------------------------
  "handling.spara": "Guardar",
  "handling.avbryt": "Cancelar",
  "handling.fortsatt": "Continuar",
  "handling.tillbaka": "Voltar",
  "handling.dokumentera": "Documentar",
  "handling.fotografera": "Fotografar",
  "handling.spela_in": "Gravar vídeo",
  "handling.undantag": "Documentar uma exceção",
  "handling.undantag.skal": "Motivo da exceção (obrigatório)",
  "handling.exportera": "Exportar",
  "handling.skriv_ut": "Imprimir",

  // ---- Medição ------------------------------------------------------------
  "matning.varde": "Valor",
  "matning.enhet": "Unidade",
  "matning.matdon": "Instrumento",
  "matning.matdon.valj": "Selecionar instrumento",
  "matning.matdon.okant": "Instrumento desconhecido. Registá-lo antes de guardar a medição.",
  "matning.kalibrerad_till": "Calibrado até",

  // ---- Relatório ----------------------------------------------------------
  "rapport.rubrik": "Relatório do processo",
  "rapport.sammanfattning": "Resumo",
  "rapport.evidens": "Evidência",
  "rapport.atgarder": "Ações",
  "rapport.harledd":
    "Derivado do registo do processo. As observações e as medições são apresentadas sem conclusões que careçam de fundamento.",

  // ---- Idioma -------------------------------------------------------------
  "sprak.valj": "Idioma",
  "sprak.granskat": "Revisto",
  "sprak.ogranskat": "Não revisto",
  "sprak.tackning": "{procent} % da interface",

  "metodik.ogranskad":
    "O texto dos procedimentos não foi revisto por um especialista técnico em {sprak}. Os passos e os pontos de controlo são apresentados em inglês onde não existe tradução revista — uma tradução não revista de uma instrução de segurança é pior do que uma em língua estrangeira, porque não parece estrangeira.",
  "metodik.pa_engelska": "Apresentado em inglês — sem tradução revista em {sprak}",

  // ---- Site público (webb.) ----------------------------------------------
  "webb.nav.oversikt": "Visão geral",
  "webb.ansok": "Solicitar conta",
  "webb.loggain": "Iniciar sessão",
  "webb.fot.impressum": "Informação legal",
  "webb.fot.dataskydd": "Privacidade",
  "webb.fot.villkor": "Condições",
  "webb.fot.tillganglighet": "Acessibilidade",
  "webb.fot.sprak": "Idiomas",
  "webb.fot.utgavor": "Notas de versão",

  "webb.hero.position": "Plataforma de diagnóstico guiado",
  "webb.hero.definition": "Procedimentos de diagnóstico padronizados para uma deteção de avarias repetível e verificável.",

  "webb.metod.etikett": "Metodologia",
  "webb.metod.rubrik": "O modelo ALVA",
  "webb.metod.ingress":
    "O ALVA é um método padronizado de análise, localização, verificação e ação sistemáticas. Cada decisão é rastreável, cada conclusão verificável, cada ação reproduzível.",
  "webb.fas.analysis.syfte": "Reunir evidências.",
  "webb.fas.analysis.avgransning": "Apenas factos. Nesta fase não se recolhem hipóteses.",
  "webb.fas.localization.syfte": "Isolar a avaria.",
  "webb.fas.localization.avgransning": "Estreitar a área. A causa ainda não está estabelecida.",
  "webb.fas.verification.syfte": "Confirmar a causa raiz.",
  "webb.fas.verification.avgransning": "Verifica-se a causa — não o sintoma.",
  "webb.fas.action.syfte": "Executar a ação corretiva.",
  "webb.fas.action.avgransning": "Resultado verificado e documentado. Caso contrário, a fase está incompleta.",

  "webb.drift.etikett": "Funcionamento",
  "webb.drift.rubrik": "Como funciona",
  "webb.drift.s1.rubrik": "Criar a organização",
  "webb.drift.s1.text": "O registo é submetido e analisado.",
  "webb.drift.s2.rubrik": "Os utilizadores recebem contas",
  "webb.drift.s2.text": "As funções são atribuídas pelo administrador da organização.",
  "webb.drift.s3.rubrik": "Procedimentos de diagnóstico guiados",
  "webb.drift.s3.text": "Cada processo segue um procedimento definido.",
  "webb.drift.s4.rubrik": "Verificação",
  "webb.drift.s4.text": "A causa raiz é confirmada antes da ação corretiva.",
  "webb.drift.s5.rubrik": "Documentação",
  "webb.drift.s5.text": "O relatório é gerado a partir do registo do processo.",
  "webb.drift.s6.rubrik": "Melhoria contínua",
  "webb.drift.s6.text": "Resultados verificados refinam os procedimentos seguintes.",

  "webb.larande.etikett": "Capacidade",
  "webb.larande.rubrik": "Aprendizagem da organização",
  "webb.larande.p1":
    "A plataforma refina continuamente os procedimentos de diagnóstico com a experiência operacional verificada da sua própria organização.",
  "webb.larande.p2":
    "Cada diagnóstico concluído alimenta a orientação seguinte. Só se usam resultados verificados — um processo encerrado sem causa raiz confirmada não contribui com nada, por conceção.",
  "webb.larande.p3":
    "A base de conhecimento pertence à organização. É derivada dos seus processos, dos seus procedimentos e da sua documentação, e não é agregada entre clientes.",
  "webb.larande.block": "Derivada de",
  "webb.larande.k1": "Causas raiz verificadas",
  "webb.larande.k2": "Ações corretivas confirmadas",
  "webb.larande.k3": "Categorias de avarias recorrentes",
  "webb.larande.k4": "Registos de conclusão de procedimentos",
  "webb.larande.k5": "Documentação da organização",

  "webb.rapport.etikett": "Relatórios",
  "webb.rapport.rubrik": "Relatório trimestral de melhoria",
  "webb.rapport.ingress":
    "Uma vez por trimestre, a plataforma responde a seis perguntas sobre o próprio trabalho da oficina. Cada resposta é derivada do registo de processos — nada é estimado e nada é perguntado a ninguém.",
  "webb.rapport.f1": "Que avarias diagnosticamos agora corretamente à primeira?",
  "webb.rapport.f2": "Com que frequência uma causa suspeita se revela a verdadeira?",
  "webb.rapport.f3": "Que avarias continuam a voltar na frota?",
  "webb.rapport.f4": "Que passos do procedimento são saltados, e porquê?",
  "webb.rapport.f5": "O que sabe a oficina agora que não sabia no trimestre passado?",
  "webb.rapport.f6": "Os processos são encerrados, verificados e documentados — ou apenas encerrados?",

  "webb.pris.etikett": "Comercial",
  "webb.pris.rubrik": "Licenciamento",
  "webb.pris.komponent": "Componente",
  "webb.pris.grund": "Base",
  "webb.pris.plattform": "Licença de plataforma",
  "webb.pris.plattform.grund": "Por organização, anual",
  "webb.pris.anvandare": "Licenças de utilizador",
  "webb.pris.anvandare.grund": "Por utilizador ativo, mensal",
  "webb.pris.moduler": "Módulos empresariais",
  "webb.pris.moduler.grund": "Opcionais, por módulo",
  "webb.pris.betalning": "Sem pagamento online. Sem adesão a subscrição. A faturação segue-se à análise do pedido.",
  "webb.pris.aktivering": "Sequência de ativação",
  "webb.pris.a1": "A organização submete o registo.",
  "webb.pris.a2": "O pedido é analisado.",
  "webb.pris.a3": "A fatura é emitida.",
  "webb.pris.a4": "O pagamento é registado.",
  "webb.pris.a5": "A organização é ativada.",
  "webb.pris.a6": "Os utilizadores adicionais são faturados mensalmente.",

  "webb.kallor.etikett": "Infraestrutura",
  "webb.kallor.rubrik": "Infraestrutura operacional de conhecimento",
  "webb.kallor.p1":
    "O ALVA usa as fontes de conhecimento autorizadas da própria organização. A arquitetura é neutra quanto ao fornecedor: cada fonte implementa a mesma interface e nenhum fornecedor é pressuposto.",
  "webb.kallor.p2":
    "Uma instalação beta trabalha apenas com documentação interna. Fornecedores externos são ativados mais tarde através de conectores separados, sem alteração do núcleo da plataforma.",
  "webb.kallor.block": "Ordem de resolução das fontes",
  "webb.kallor.k1": "Procedimentos internos da empresa",
  "webb.kallor.k2": "Documentação OEM",
  "webb.kallor.k3": "Boletins técnicos",
  "webb.kallor.k4": "Informação de garantia",
  "webb.kallor.k5": "Manuais de oficina",
  "webb.kallor.k6": "Diagnósticos históricos verificados",
  "webb.kallor.k7": "Boas práticas da organização",

  "webb.login.etikett": "Acesso",
  "webb.login.demo":
    "Este início de sessão não autentica nada. Escreva qualquer coisa em E-mail e Palavra-passe e prima Entrar — não é preciso conta, e o portal por trás apresenta dados de exemplo fixos. Ligada a uma instância da plataforma, esta página autentica-se junto dela, e sem sessão válida o portal está fechado.",
  "webb.login.losenord": "Palavra-passe",
  "webb.login.ofullstandigt": "Autenticação incompleta. E-mail e palavra-passe são obrigatórios.",
  "webb.login.misslyckades": "A autenticação falhou.",
  "webb.login.logga_in": "Entrar",
  "webb.login.loggar_in": "A entrar",
  "webb.login.glomt": "Recuperar palavra-passe",

  "webb.ansokan.etikett": "Registo",
  "webb.ansokan.demo":
    "Nada é enviado. Submeter este formulário não guarda nada, não notifica ninguém e não cria nenhum pedido — ainda não há receção por trás. A descrição abaixo diz como o registo deve funcionar, não o que acontece hoje.",
  "webb.ansokan.avsikt": "Funcionamento previsto: os pedidos são analisados manualmente e nesta fase não é cobrado qualquer pagamento.",
  "webb.falt.foretag": "Empresa",
  "webb.falt.orgnummer": "Número de registo comercial",
  "webb.falt.kontakt": "Pessoa de contacto",
  "webb.falt.epost": "E-mail",
  "webb.falt.telefon": "Telefone",
  "webb.falt.tekniker": "Número de técnicos",
  "webb.falt.bransch": "Setor",
  "webb.falt.land": "País",
  "webb.falt.anvandare": "Número previsto de utilizadores",
  "webb.falt.noteringar": "Notas",
  "webb.falt.kravs": "(obrigatório)",
  "webb.ansokan.skicka": "Submeter o pedido",
  "webb.ansokan.mottagen.etikett": "Pedido",
  "webb.ansokan.mottagen": "Submetido",
  "webb.ansokan.mottagen.demo":
    "Nada foi transmitido e ninguém foi notificado. A referência abaixo foi calculada no seu navegador a partir do que escreveu e não existe em mais lado nenhum — desaparecerá quando fechar esta página.",
  "webb.ansokan.status": "Estado",
  "webb.ansokan.referens": "Referência",
  "webb.ansokan.granskning":
    "Os pedidos são analisados manualmente. A fatura é emitida após a aprovação. A organização é ativada quando o pagamento é registado.",

  "webb.sprak.etikett": "Localização",
  "webb.sprak.rubrik": "Idiomas",
  "webb.sprak.ingress":
    "O inglês é o idioma predefinido e o idioma de origem. Seguem-se nove traduções. O que a plataforma não faz é afirmar que uma interface traduzida significa um método traduzido.",
  "webb.sprak.princip.etikett": "Princípio",
  "webb.sprak.princip.rubrik": "Dois tipos de texto",
  "webb.sprak.granssnitt.rubrik": "Texto de interface",
  "webb.sprak.granssnitt.beteckning": "Reverte em silêncio",
  "webb.sprak.granssnitt.text":
    "Etiquetas, botões, estados. Finito, raramente alterado. Uma cadeia de caracteres em inglês que chega a um utilizador alemão é uma irritação, não um perigo — por isso uma tradução em falta reverte para o inglês sem comentário.",
  "webb.sprak.metodik.rubrik": "Texto de procedimento",
  "webb.sprak.metodik.beteckning": "Nunca reverte em silêncio",
  "webb.sprak.metodik.text":
    "Instruções para trabalhar num veículo. Aqui uma tradução não revista é pior do que uma em língua estrangeira — porque o inglês parece estrangeiro, enquanto uma má tradução parece uma instrução. É mostrada em inglês e assinalada, com o idioma nomeado.",
  "webb.sprak.invariant":
    "O método em si nunca é traduzido. Os nomes das fases e as palavras de estado são a estrutura do ALVA e leem-se de forma idêntica em todos os países, para que um auditor possa ler um processo romeno e um alemão sem saber em que idioma a oficina trabalha.",
  "webb.sprak.tackning.etikett": "Cobertura",
  "webb.sprak.tackning.rubrik": "O que está traduzido, e o que está revisto",
  "webb.sprak.kolumn.sprak": "Idioma",
  "webb.sprak.kolumn.granssnitt": "Interface",
  "webb.sprak.kolumn.granskat": "Método revisto por um especialista",
  "webb.sprak.granskat.ja": "Sim",
  "webb.sprak.granskat.nej": "Não — texto de procedimento em inglês",
  "webb.sprak.matt":
    "A cobertura da interface é medida, não estimada: um teste faz falhar a compilação se faltar alguma chave em algum idioma. O estado de revisão é uma afirmação sobre pessoas, não sobre ficheiros, e é definido à mão.",
  "webb.sprak.kallsprak":
    "O texto de procedimento em inglês é uma tradução da fonte sueca e ainda não foi lido por um especialista que exerce o ofício. É sujeito ao mesmo padrão dos outros nove idiomas, e aqui faz-se sobre ele a mesma declaração em vez de o excetuar em silêncio por ser a fonte.",
  "webb.sprak.bevis.etikett": "Verificação",
  "webb.sprak.bevis.rubrik": "As frases que param um processo",
  "webb.sprak.bevis.ingress":
    "Estas são as frases que recusam a um técnico o encerramento de um processo. Uma recusa que ninguém entende é uma recusa sem saída — por isso são as frases certas para julgar uma tradução.",
  "webb.sprak.ej_granskad": "Não revisto",
  "webb.sprak.granskad": "Revisto",
  "webb.sprak.granskad.text":
    "O texto de procedimento em {sprak} foi lido por um especialista que exerce o ofício. Os passos e os pontos de controlo são mostrados em {sprak} em toda a plataforma.",
  "webb.sprak.val.etikett": "Funcionamento",
  "webb.sprak.val.rubrik": "Como o idioma é escolhido",
  "webb.sprak.val.s1.rubrik": "Preferência do utilizador",
  "webb.sprak.val.s1.text": "O que a pessoa selecionou.",
  "webb.sprak.val.s2.rubrik": "Definição da organização",
  "webb.sprak.val.s2.text": "O idioma de documentação da oficina.",
  "webb.sprak.val.s3.rubrik": "Idioma do navegador",
  "webb.sprak.val.s3.text": "O primeiro idioma que a plataforma reconhece.",
  "webb.sprak.val.s4.rubrik": "Inglês",
  "webb.sprak.val.s4.text": "O predefinido, e a origem.",
  "webb.sprak.val.notering":
    "A organização vem deliberadamente antes do navegador. Uma oficina na Alemanha com um técnico polaco precisa de um único idioma de documentação — o processo não pode mudar de idioma conforme quem escreveu a linha.",

  // ---- Kunddelningen (ALVA-PROC-0030 · delningsvyn) -----------------------
  "sammanfattning.objekt": "O caso diz respeito a {objekt}.",
  "sammanfattning.objekt_utan_namn": "O caso diz respeito a um objeto identificado.",
  "sammanfattning.objekt_saknas": "O objeto não está identificado no registo.",
  "sammanfattning.kundbeskrivning": "O cliente descreveu: «{text}»",
  "sammanfattning.repro.ja": "O sintoma foi reproduzido.",
  "sammanfattning.repro.delvis": "O sintoma pôde ser parcialmente reproduzido.",
  "sammanfattning.repro.nej":
    "O sintoma não pôde ser reproduzido nas condições presentes durante o exame.",
  "sammanfattning.repro.dokumenterad": "A reprodução está documentada.",
  "sammanfattning.orsak_ej_faststalld": "A causa não pôde ser determinada: {motivering}",
  "sammanfattning.avvikelse": "Anomalia constatada: {avvikelse}",
  "sammanfattning.bedomd_orsak": "Causa avaliada: {kategori}.",
  "sammanfattning.motivering": "Fundamentação: {motivering}",
  "sammanfattning.atgard_utford": "Intervenção realizada: {beskrivning}",
  "sammanfattning.atgard_ej_utford": "Nenhuma intervenção realizada: {motivering}",
  "sammanfattning.kvalitet.symptomet_borta": "No controlo de qualidade o sintoma tinha desaparecido.",
  "sammanfattning.kvalitet.kvarstar": "No controlo de qualidade o sintoma persistia.",
  "sammanfattning.kvalitet.delvis": "No controlo de qualidade o sintoma persistia parcialmente.",
  "sammanfattning.kvalitet.ej_verifierbar": "O controlo de qualidade não pôde verificar o resultado.",
  "sammanfattning.kvalitet.dokumenterad": "O controlo de qualidade está documentado.",
  "sammanfattning.kvarstaende": "Pendente: {text}",
  "sammanfattning.rad.oidentifierat": "Objeto não identificado",
  "sammanfattning.rad.pagaende": "{vad} — em curso.",
  "sammanfattning.rad.utan_orsak": "{vad} — encerrado sem causa determinada.",
  "sammanfattning.rad.avslutat": "{vad} — encerrado.",
  "delning.rubrik.fall": "Caso",
  "delning.rubrik.delat": "Caso partilhado",
  "delning.status.avslutat": "Encerrado",
  "delning.status.pagaende": "Diagnóstico em curso",
  "delning.identitet.arbetsorder": "Ordem de reparação",
  "delning.identitet.claim": "Claim",
  "delning.identitet.skadenummer": "N.º do sinistro",
  "delning.identitet.regnr": "Matrícula",
  "delning.identitet.vin": "VIN",
  "delning.identitet.miltal": "Quilometragem",
  "delning.identitet.ansvarig": "Técnico responsável",
  "delning.identitet.status": "Estado",
  "delning.rubrik.sammanfattning": "Resumo",
  "delning.rubrik.slutsats": "Conclusão e fundamentação",
  "delning.slutsats.ej_faststalld": "Razão pela qual a causa não pôde ser determinada",
  "delning.slutsats.motivering": "Fundamentação",
  "delning.slutsats.uteslutet": "Alternativas afastadas",
  "delning.slutsats.atgardsval": "Escolha da intervenção",
  "delning.slutsats.kvarstaende": "Incerteza remanescente",
  "delning.rubrik.felbeskrivning": "Descrição da avaria pelo cliente",
  "delning.rubrik.forslag": "Intervenção proposta",
  "delning.forslag.kostnad": "Custo estimado: {kostnad}",
  "delning.forslag.beslut": "A sua decisão: {beslut}",
  "delning.forslag.via": "(registada via {kanal})",
  "delning.forslag.vantar":
    "A aguardar a sua decisão — contacte a oficina para aprovar ou recusar.",
  "delning.beslut.rubrik": "A sua decisão para a oficina",
  "delning.beslut.godkann": "Aprovar a intervenção",
  "delning.beslut.avboj": "Recusar",
  "delning.beslut.kommentar": "Comentário (opcional)",
  "delning.beslut.motivering": "Breve fundamentação (opcional)",
  "delning.beslut.skickar": "A enviar …",
  "delning.beslut.skicka": "Enviar a decisão",
  "delning.beslut.info":
    "A decisão fica registada no caso e não pode ser alterada aqui — contacte a oficina se mudar de ideias.",
  "delning.beslut.godkant": "Aprovada",
  "delning.beslut.avbojt": "Recusada",
  "delning.beslut.delvis": "Parcialmente aprovada",
  "delning.beslut.fel.plattform": "A decisão não pode ser dada aqui — contacte a oficina.",
  "delning.beslut.fel.registrering": "Não foi possível registar a decisão — tente novamente.",
  "delning.beslut.fel.forbindelse": "Não foi possível enviar a decisão — verifique a ligação.",
  "delning.rubrik.laget": "Estado atual",
  "delning.rubrik.video": "Vídeo",
  "delning.rubrik.bilder": "Imagens",
  "delning.rubrik.matningar": "Medições",
  "delning.rubrik.tidslinje": "Cronologia",
  "delning.tidslinje.arbetssprak": "As entradas são apresentadas textualmente, na língua de trabalho da oficina.",
  "delning.rubrik.nasta": "Próximo passo recomendado",
  "delning.rubrik.arbetstid": "Tempo de trabalho",
  "delning.fot": "Caso #{nummer} · iniciado {datum} · gerado a partir do registo do caso",
  "delning.notis.kund":
    "Vista em direto, só de leitura, a partir da oficina — a página atualiza-se automaticamente à medida que nova informação é registada.",
  "delning.notis.partner":
    "Vista em direto só de leitura (nível parceiro) — inclui hipóteses técnicas, claramente assinaladas como não verificadas. Atualiza-se automaticamente.",
  "delning.notis.intern":
    "Vista em direto só de leitura (nível interno) — visibilidade total do caso. Atualiza-se automaticamente.",
  "delning.hamtar": "A obter o caso …",
  "delning.saknas": "O caso não está disponível. Confirme a ligação com a oficina — a partilha pode ter sido revogada.",
};
