// ALVA-SPEC-060 · Svenska.
//
// Hemmamarknadens språk och det enda utöver engelska där metodik-
// innehållet är läst av någon som kan yrket. Därför `granskat: true` i
// SPRAK — inte för att svenskan är bättre skriven än tyskan här, utan
// för att den är kontrollerad av en fackman och tyskan inte är det.
//
// Fas- och statusord saknas medvetet. De är ALVA:s struktur och skrivs
// likadant på varje språk (ALVA-SPEC-001 §2). Se index.mjs.

export const SV = {
  // ---- Evidensgrader ------------------------------------------------------
  "evidens.E1": "Observation",
  "evidens.E2": "Fotografi",
  "evidens.E3": "Video med ljud",
  "evidens.E4": "Mätning, kalibrerat mätdon",
  "evidens.E5": "Dokument",
  "evidens.ej_kalibrerad": "kalibrering saknas eller har gått ut",
  "evidens.ej_angivet": "mätdon ej angivet",
  "evidens.ej_fotograferad": "inmatad, ej fotograferad",

  // ---- Kvalitetsgrinden ---------------------------------------------------
  "grind.objekt": "Fordonets eller objektets identitet verifierad",
  "grind.historik": "Fordonets historik kontrollerad, eller den uteblivna kontrollen motiverad",
  "grind.historik.nekad": "En nekad historikkontroll kräver ett angivet skäl.",
  "grind.historik.saknas": "Ingen historikkontroll dokumenterad.",
  "grind.matarstallning.ingaende": "Ingående mätarställning fotograferad",
  "grind.matarstallning.utgaende": "Utgående mätarställning fotograferad",
  "grind.matarstallning.saknas": "Ingen mätarställning dokumenterad.",
  "grind.matarstallning.ej_foto":
    "Mätarställningen är inmatad men inte fotograferad. Fotografera mätaren, eller ange varför det inte är möjligt.",
  "grind.reproducering": "Symtomverifiering: reproducerat, eller dokumenterat som ej reproducerbart",
  "grind.felorsak": "Grundorsaksanalys dokumenterad",
  "grind.atgard": "Åtgärd dokumenterad, eller den uteblivna åtgärden motiverad",
  "grind.atgard.saknas": "Varken utförd åtgärd eller skäl till att den uteblivit är dokumenterat.",
  "grind.kundbeslut": "Kundens beslut om förslaget registrerat",
  "grind.kundbeslut.avbojt": "Arbete utfört trots avböjt förslag",
  "grind.kundbeslut.avbojt.detalj": "Kunden avböjde förslaget, men arbete är dokumenterat som utfört.",
  "grind.kvalitetskontroll": "Kvalitetskontroll utförd — symtomet verifierat avhjälpt",
  "grind.kontroller": "Metodikens kontrollpunkter: evidens, eller dokumenterat undantag",
  "grind.foton": "Foton finns för de kontrollpunkter som kräver det",
  "grind.slutsats": "Slutsats (ALVA-RULE-200)",
  "grind.hogvolt.behorighet": "Högvoltsbehörighet bekräftad",
  "grind.hogvolt.spanningslos": "Fordonet spänningslöst enligt tillverkarens procedur, spänningsfrihet verifierad genom mätning",
  "grind.regelpaket": "Regelpaketets signatur stämmer inte — avslut spärrat.",
  "grind.regelpaket.osignerat": "Ett externt regelpaket används utan signatur — avslut spärrat.",
  "grind.evidens": "Evidensnivå över E0",
  "grind.evidens.saknas": "Ingen evidens av något slag finns i loggen.",
  "grind.foton.detalj": "{kontroller} kontrollpunkter kräver foto, {foton} foton i loggen.",
  "grind.anmarkning.bevis": "Anmärkningar bär visuellt bevis",
  "grind.anmarkning.saknas": "Ett åtgärdat fel måste vara antecknat som en anmärkning",
  "grind.anmarkning.saknas.detalj": "En åtgärd har utförts och en felorsak fastställts, men ingen kontroll är märkt som anmärkning. Det som lagades finns då ingenstans i loggen som ett fynd.",
  "grind.sparr.ej_uppfyllt": "Säkerhetskravet är inte uppfyllt.",
  "grind.sparr.kringgangen": "En säkerhetsförutsättning besvarades och uppfylldes inte. Den kan inte avföras genom ett metodikbyte — uppfyll den, eller om metodiken var fel skulle säkerhetsfrågan inte ha besvarats under den.",
  "grind.arendetyp.okant": "Okänt krav i regelpaketet: {krav}",
  "grind.arendetyp.krav": "Krav för ärendetypen: {krav}",
  "grind.sakerhet": "Konfidensnivån inom vad underlaget bär",
  "grind.sakerhet.detalj": "Angiven konfidens ({niva}) överstiger vad underlaget bär ({tak}). Komplettera underlaget, eller sänk nivån — ärlig osäkerhet är information.",
  "grind.eskalering": "Tekniska eskaleringar besvarade",
  "grind.eskalering.detalj": "En eskalering är öppen ({referens}). Invänta svaret och dokumentera det innan ärendet avslutas.",


  // ---- Slutsatsen (ALVA-RULE-200) -----------------------------------------
  "slutsats.rubrik": "Slutsats",
  "slutsats.konstaterat": "Vad som är konstaterat",
  "slutsats.evidens": "Vilken evidens som bär det",
  "slutsats.avfardat": "Vilka hypoteser som avfärdats, och varför",
  "slutsats.osakert": "Vad som fortfarande är osäkert",
  "slutsats.ickesvar": "Det är inte ett svar. Ange vad som är konstaterat och vilken evidens som bär det.",
  "slutsats.falt.motivering": "Motivering",
  "slutsats.falt.motivering_ej": "Skäl till att orsaken inte fastställts",
  "slutsats.falt.uteslutet": "Uteslutna alternativ",
  "slutsats.falt.kvarstaende": "Kvarstående osäkerhet",
  "slutsats.falt.atgardsval": "Val av åtgärd",
  "slutsats.saknas": "{falt} saknas.",
  "slutsats.ickesvar.falt": "{falt}: ”{text}” är inget skäl. Beskriv vad som faktiskt gäller och varför.",
  "slutsats.for_kort": "{falt} är för kort ({langd} av minst {minsta} tecken) för att gå att granska i efterhand.",
  "slutsats.utan_varfor": "{falt} anger vad, men inte varför. Knyt slutsatsen till evidensen — vad i den gör att det här följer?",
  "slutsats.utan_slutsats": "Ärendet kan inte avslutas utan en slutsats. Motivera varför slutsatsen följer av underlaget.",
  "slutsats.hypotes_obemott": "Hypotesen ”{text}” finns i loggen men bemöts inte. Ange varför den avfärdades, eller varför den kvarstår.",


  // ---- Ärendeflödet -------------------------------------------------------
  "arende.nytt": "Nytt ärende",
  "arende.oppna": "Öppna ärenden",
  "arende.avslutade": "Avslutade ärenden",
  "arende.avsluta": "Avsluta ärendet",
  "arende.avslutat": "Ärendet avslutat",
  "arende.kan_ej_avslutas": "Ärendet kan ännu inte avslutas",
  "arende.hinder": "Kvarstår före avslut",
  "arende.overlamna": "Lämna över",
  "arende.ansvarig": "Ansvarig",

  // ---- Förkontroll --------------------------------------------------------
  "pre.rubrik": "Förkontroll — innan arbetet börjar",
  "pre.historik.fraga": "Är fordonets historik kontrollerad? (tidigare arbeten, återkommande fel, TSB:er, kampanjer)",
  "pre.historik.ja": "Ja — kontrollerad",
  "pre.historik.nej": "Nej",
  "pre.historik.skal": "Skäl till att historiken inte kontrollerats (obligatoriskt)",
  "pre.historik.relevant": "Relevanta tidigare arbeten (valfritt — orsakskedja)",
  "pre.matarstallning": "Mätarställning",
  "pre.fotografera": "Fotografera instrumentpanelen",
  "pre.felbeskrivning": "Kundens felbeskrivning verifierad",
  "pre.observationer": "Något annat vid mottagandet?",

  // ---- Handlingar ---------------------------------------------------------
  "handling.spara": "Spara",
  "handling.avbryt": "Avbryt",
  "handling.fortsatt": "Fortsätt",
  "handling.tillbaka": "Tillbaka",
  "handling.dokumentera": "Dokumentera",
  "handling.fotografera": "Fotografera",
  "handling.spela_in": "Spela in video",
  "handling.undantag": "Dokumentera ett undantag",
  "handling.undantag.skal": "Skäl till undantaget (obligatoriskt)",
  "handling.exportera": "Exportera",
  "handling.skriv_ut": "Skriv ut",

  // ---- Mätning ------------------------------------------------------------
  "matning.varde": "Värde",
  "matning.enhet": "Enhet",
  "matning.matdon": "Mätdon",
  "matning.matdon.valj": "Välj mätdon",
  "matning.matdon.okant": "Okänt mätdon. Registrera det innan mätningen sparas.",
  "matning.kalibrerad_till": "Kalibrerad t.o.m.",

  // ---- Rapport ------------------------------------------------------------
  "rapport.rubrik": "Ärenderapport",
  "rapport.sammanfattning": "Sammanfattning",
  "rapport.evidens": "Evidens",
  "rapport.atgarder": "Åtgärder",
  "rapport.harledd":
    "Härledd ur ärendeloggen. Observationer och mätningar redovisas utan slutsatser som saknar stöd.",

  // ---- Språk --------------------------------------------------------------
  "sprak.valj": "Språk",
  "sprak.granskat": "Granskat",
  "sprak.ogranskat": "Ej granskat",
  "sprak.tackning": "{procent} % av gränssnittet",

  "metodik.ogranskad":
    "Metodiktexten är inte granskad av en fackman på {sprak}. Steg och kontrollpunkter visas på engelska där ingen granskad översättning finns — en ogranskad översättning av en säkerhetsinstruktion är sämre än en på främmande språk, därför att den inte ser främmande ut.",
  "metodik.pa_engelska": "Visas på engelska — ingen granskad översättning på {sprak}",

  // ---- Publika webbplatsen (webb.) ---------------------------------------
  "webb.nav.oversikt": "Översikt",
  "webb.ansok": "Ansök om konto",
  "webb.loggain": "Logga in",
  "webb.fot.impressum": "Impressum",
  "webb.fot.dataskydd": "Dataskydd",
  "webb.fot.villkor": "Villkor",
  "webb.fot.tillganglighet": "Tillgänglighet",
  "webb.fot.sprak": "Språk",
  "webb.fot.utgavor": "Versionsinformation",

  "webb.hero.position": "Guidad diagnostikplattform",
  "webb.hero.definition": "Standardiserade diagnosprocedurer för repeterbar och verifierbar felsökning.",

  "webb.metod.etikett": "Metodik",
  "webb.metod.rubrik": "ALVA-modellen",
  "webb.metod.ingress":
    "ALVA är en standardiserad metod för systematisk analys, lokalisering, verifiering och åtgärd. Varje beslut är spårbart, varje slutsats verifierbar, varje åtgärd reproducerbar.",
  "webb.fas.analysis.syfte": "Samla evidens.",
  "webb.fas.analysis.avgransning": "Enbart fakta. Hypoteser samlas inte i denna fas.",
  "webb.fas.localization.syfte": "Ringa in felet.",
  "webb.fas.localization.avgransning": "Avgränsa området. Orsaken är ännu inte fastställd.",
  "webb.fas.verification.syfte": "Bekräfta grundorsaken.",
  "webb.fas.verification.avgransning": "Orsaken verifieras — inte symtomet.",
  "webb.fas.action.syfte": "Utför åtgärden.",
  "webb.fas.action.avgransning": "Resultatet verifierat och dokumenterat. Annars är fasen inte avslutad.",

  "webb.drift.etikett": "Drift",
  "webb.drift.rubrik": "Så fungerar det",
  "webb.drift.s1.rubrik": "Skapa organisation",
  "webb.drift.s1.text": "Registreringen skickas in och granskas.",
  "webb.drift.s2.rubrik": "Användarna får konton",
  "webb.drift.s2.text": "Roller tilldelas av organisationens administratör.",
  "webb.drift.s3.rubrik": "Guidade diagnosprocedurer",
  "webb.drift.s3.text": "Varje ärende följer en definierad procedur.",
  "webb.drift.s4.rubrik": "Verifiering",
  "webb.drift.s4.text": "Grundorsaken bekräftas före åtgärd.",
  "webb.drift.s5.rubrik": "Dokumentation",
  "webb.drift.s5.text": "Rapporten genereras ur ärendeloggen.",
  "webb.drift.s6.rubrik": "Ständig förbättring",
  "webb.drift.s6.text": "Verifierade utfall förfinar kommande procedurer.",

  "webb.larande.etikett": "Förmåga",
  "webb.larande.rubrik": "Organisationens lärande",
  "webb.larande.p1":
    "Plattformen förfinar löpande diagnosprocedurerna med verifierad drifterfarenhet från den egna organisationen.",
  "webb.larande.p2":
    "Varje slutförd diagnos bidrar till kommande vägledning. Endast verifierade utfall används — ett ärende som stängts utan bekräftad grundorsak bidrar med ingenting, avsiktligt.",
  "webb.larande.p3":
    "Kunskapsbasen tillhör organisationen. Den härleds ur era ärenden, era procedurer och er dokumentation, och den aggregeras inte över kunder.",
  "webb.larande.block": "Härledd ur",
  "webb.larande.k1": "Verifierade grundorsaker",
  "webb.larande.k2": "Bekräftade åtgärder",
  "webb.larande.k3": "Återkommande felkategorier",
  "webb.larande.k4": "Genomförda procedurer",
  "webb.larande.k5": "Organisationens dokumentation",

  "webb.rapport.etikett": "Rapportering",
  "webb.rapport.rubrik": "Kvartalsvis förbättringsrapport",
  "webb.rapport.ingress":
    "En gång i kvartalet besvarar plattformen sex frågor om verkstadens eget arbete. Varje svar härleds ur ärendeloggen — ingenting uppskattas, och ingen tillfrågas.",
  "webb.rapport.f1": "Vilka fel diagnostiserar vi nu rätt på första försöket?",
  "webb.rapport.f2": "Hur ofta visar sig en misstänkt orsak vara den verkliga?",
  "webb.rapport.f3": "Vilka fel återkommer i flottan?",
  "webb.rapport.f4": "Vilka procedursteg hoppas över, och varför?",
  "webb.rapport.f5": "Vad vet verkstaden nu som den inte visste förra kvartalet?",
  "webb.rapport.f6": "Avslutas, verifieras och dokumenteras ärendena — eller avslutas de bara?",

  "webb.pris.etikett": "Kommersiellt",
  "webb.pris.rubrik": "Licensiering",
  "webb.pris.komponent": "Komponent",
  "webb.pris.grund": "Grund",
  "webb.pris.plattform": "Plattformslicens",
  "webb.pris.plattform.grund": "Per organisation, årsvis",
  "webb.pris.anvandare": "Användarlicenser",
  "webb.pris.anvandare.grund": "Per aktiv användare, månadsvis",
  "webb.pris.moduler": "Företagsmoduler",
  "webb.pris.moduler.grund": "Valfria, per modul",
  "webb.pris.betalning": "Ingen onlinebetalning. Ingen prenumerationsregistrering. Fakturering följer på granskning av ansökan.",
  "webb.pris.aktivering": "Aktiveringssekvens",
  "webb.pris.a1": "Organisationen skickar in registreringen.",
  "webb.pris.a2": "Ansökan granskas.",
  "webb.pris.a3": "Faktura ställs ut.",
  "webb.pris.a4": "Betalningen registreras.",
  "webb.pris.a5": "Organisationen aktiveras.",
  "webb.pris.a6": "Ytterligare användare faktureras månadsvis.",

  "webb.kallor.etikett": "Infrastruktur",
  "webb.kallor.rubrik": "Operativ kunskapsinfrastruktur",
  "webb.kallor.p1":
    "ALVA använder organisationens egna auktoriserade kunskapskällor. Arkitekturen är leverantörsneutral: varje källa implementerar samma gränssnitt, och ingen leverantör förutsätts.",
  "webb.kallor.p2":
    "En betainstallation arbetar enbart mot intern dokumentation. Externa leverantörer aktiveras senare via separata anslutningar, utan ändring i plattformskärnan.",
  "webb.kallor.block": "Källornas prioritetsordning",
  "webb.kallor.k1": "Interna företagsprocedurer",
  "webb.kallor.k2": "OEM-dokumentation",
  "webb.kallor.k3": "Tekniska bulletiner",
  "webb.kallor.k4": "Garantiinformation",
  "webb.kallor.k5": "Verkstadshandböcker",
  "webb.kallor.k6": "Historiska verifierade diagnoser",
  "webb.kallor.k7": "Organisationens bästa praxis",

  "webb.login.etikett": "Åtkomst",
  "webb.login.demo":
    "Den här inloggningen autentiserar ingenting. Skriv vad som helst i E-post och Lösenord och tryck Logga in — inget konto behövs, och portalen bakom visar fasta exempeldata. Ansluten till en plattformsinstans autentiserar sidan mot den, och portalen är stängd utan giltig session.",
  "webb.login.losenord": "Lösenord",
  "webb.login.ofullstandigt": "Autentisering ofullständig. E-post och lösenord krävs.",
  "webb.login.misslyckades": "Autentisering misslyckades.",
  "webb.login.logga_in": "Logga in",
  "webb.login.loggar_in": "Loggar in",
  "webb.login.glomt": "Glömt lösenord",

  "webb.ansokan.etikett": "Registrering",
  "webb.ansokan.demo":
    "Ingenting skickas. Att skicka formuläret lagrar ingenting, meddelar ingen och skapar ingen ansökan — det finns ännu inget mottagande system bakom det. Beskrivningen nedan anger hur registreringen är avsedd att fungera, inte vad som sker i dag.",
  "webb.ansokan.avsikt": "Avsedd drift: ansökningar granskas manuellt och ingen betalning tas i detta skede.",
  "webb.falt.foretag": "Företag",
  "webb.falt.orgnummer": "Organisationsnummer",
  "webb.falt.kontakt": "Kontaktperson",
  "webb.falt.epost": "E-post",
  "webb.falt.telefon": "Telefon",
  "webb.falt.tekniker": "Antal tekniker",
  "webb.falt.bransch": "Bransch",
  "webb.falt.land": "Land",
  "webb.falt.anvandare": "Förväntat antal användare",
  "webb.falt.noteringar": "Noteringar",
  "webb.falt.kravs": "(obligatoriskt)",
  "webb.ansokan.skicka": "Skicka ansökan",
  "webb.ansokan.mottagen.etikett": "Ansökan",
  "webb.ansokan.mottagen": "Inskickad",
  "webb.ansokan.mottagen.demo":
    "Ingenting skickades och ingen underrättades. Referensen nedan beräknades i er webbläsare ur det ni skrev och finns ingen annanstans — den är borta när ni stänger sidan.",
  "webb.ansokan.status": "Status",
  "webb.ansokan.referens": "Referens",
  "webb.ansokan.granskning":
    "Ansökningar granskas manuellt. Faktura ställs ut vid godkännande. Organisationen aktiveras när betalningen registrerats.",

  "webb.sprak.etikett": "Lokalisering",
  "webb.sprak.rubrik": "Språk",
  "webb.sprak.ingress":
    "Engelska är standard och källspråk. Nio översättningar följer. Vad plattformen inte gör är att påstå att ett översatt gränssnitt betyder en översatt metod.",
  "webb.sprak.princip.etikett": "Princip",
  "webb.sprak.princip.rubrik": "Två sorters text",
  "webb.sprak.granssnitt.rubrik": "Gränssnittstext",
  "webb.sprak.granssnitt.beteckning": "Faller tillbaka tyst",
  "webb.sprak.granssnitt.text":
    "Etiketter, knappar, statusar. Ändlig, sällan ändrad. En engelsk sträng som når en tysk användare är en irritation, inte en fara — så en saknad översättning faller tillbaka på engelska utan kommentar.",
  "webb.sprak.metodik.rubrik": "Metodiktext",
  "webb.sprak.metodik.beteckning": "Faller aldrig tillbaka tyst",
  "webb.sprak.metodik.text":
    "Instruktioner för arbete på ett fordon. Här är en ogranskad översättning sämre än en på främmande språk — därför att engelska ser främmande ut, medan en dålig översättning ser ut som en instruktion. Den visas på engelska och markeras, med språket namngivet.",
  "webb.sprak.invariant":
    "Metoden själv översätts aldrig. Fasnamn och statusord är ALVA:s struktur och läses likadant i varje land, så att en revisor kan läsa en rumänsk och en tysk ärendejournal utan att veta vilket språk verkstaden arbetar på.",
  "webb.sprak.tackning.etikett": "Täckning",
  "webb.sprak.tackning.rubrik": "Vad som är översatt, och vad som är granskat",
  "webb.sprak.kolumn.sprak": "Språk",
  "webb.sprak.kolumn.granssnitt": "Gränssnitt",
  "webb.sprak.kolumn.granskat": "Metodik granskad av fackman",
  "webb.sprak.granskat.ja": "Ja",
  "webb.sprak.granskat.nej": "Nej — metodiktext visas på engelska",
  "webb.sprak.matt":
    "Gränssnittstäckningen mäts, inte uppskattas: ett test fäller bygget om någon nyckel saknas i något språk. Granskningsstatus är ett påstående om människor, inte om filer, och sätts för hand.",
  "webb.sprak.kallsprak":
    "Den engelska metodiktexten är en översättning av den svenska källan och har ännu inte lästs av en fackman i yrket. Den hålls till samma standard som de andra nio språken, och samma besked lämnas om den här i stället för att tyst undantas för att den är källan.",
  "webb.sprak.bevis.etikett": "Verifiering",
  "webb.sprak.bevis.rubrik": "Strängarna som stoppar ett ärende",
  "webb.sprak.bevis.ingress":
    "Detta är meningarna som nekar en tekniker att avsluta ett ärende. Ett avslag ingen förstår är ett avslag utan väg igenom — så det är rätt strängar att bedöma en översättning på.",
  "webb.sprak.ej_granskad": "Ej granskad",
  "webb.sprak.granskad": "Granskad",
  "webb.sprak.granskad.text":
    "Metodiktext på {sprak} har lästs av en fackman i yrket. Steg och kontrollpunkter visas på {sprak} genomgående.",
  "webb.sprak.val.etikett": "Drift",
  "webb.sprak.val.rubrik": "Hur språket väljs",
  "webb.sprak.val.s1.rubrik": "Användarens val",
  "webb.sprak.val.s1.text": "Vad den enskilda har valt.",
  "webb.sprak.val.s2.rubrik": "Organisationens inställning",
  "webb.sprak.val.s2.text": "Verkstadens dokumentationsspråk.",
  "webb.sprak.val.s3.rubrik": "Webbläsarens språk",
  "webb.sprak.val.s3.text": "Det första språk plattformen känner igen.",
  "webb.sprak.val.s4.rubrik": "Engelska",
  "webb.sprak.val.s4.text": "Standarden, och källan.",
  "webb.sprak.val.notering":
    "Organisationen går före webbläsaren avsiktligt. En verkstad i Tyskland med en polsk tekniker behöver ett gemensamt dokumentationsspråk — journalen får inte byta språk beroende på vem som råkade skriva raden.",

  // ---- Kunddelningen (ALVA-PROC-0030 · delningsvyn) -----------------------
  "sammanfattning.objekt": "Ärendet gäller {objekt}.",
  "sammanfattning.objekt_utan_namn": "Ärendet gäller ett identifierat objekt.",
  "sammanfattning.objekt_saknas": "Objektet är inte identifierat i loggen.",
  "sammanfattning.kundbeskrivning": "Kunden beskrev: ”{text}”",
  "sammanfattning.repro.ja": "Symtomet kunde återskapas.",
  "sammanfattning.repro.delvis": "Symtomet kunde delvis återskapas.",
  "sammanfattning.repro.nej":
    "Symtomet kunde inte återskapas under de förhållanden som rådde vid undersökningen.",
  "sammanfattning.repro.dokumenterad": "Reproduceringen är dokumenterad.",
  "sammanfattning.orsak_ej_faststalld": "Orsaken kunde inte fastställas: {motivering}",
  "sammanfattning.avvikelse": "Konstaterad avvikelse: {avvikelse}",
  "sammanfattning.bedomd_orsak": "Bedömd orsak: {kategori}.",
  "sammanfattning.motivering": "Motivering: {motivering}",
  "sammanfattning.atgard_utford": "Utförd åtgärd: {beskrivning}",
  "sammanfattning.atgard_ej_utford": "Ingen åtgärd utfördes: {motivering}",
  "sammanfattning.kvalitet.symptomet_borta": "Vid kvalitetskontrollen var symtomet borta.",
  "sammanfattning.kvalitet.kvarstar": "Vid kvalitetskontrollen kvarstod symtomet.",
  "sammanfattning.kvalitet.delvis": "Vid kvalitetskontrollen kvarstod symtomet delvis.",
  "sammanfattning.kvalitet.ej_verifierbar": "Kvalitetskontrollen kunde inte verifiera utfallet.",
  "sammanfattning.kvalitet.dokumenterad": "Kvalitetskontrollen är dokumenterad.",
  "sammanfattning.kvarstaende": "Kvarstående: {text}",
  "sammanfattning.rad.oidentifierat": "Oidentifierat objekt",
  "sammanfattning.rad.pagaende": "{vad} — pågår.",
  "sammanfattning.rad.utan_orsak": "{vad} — avslutat utan fastställd orsak.",
  "sammanfattning.rad.avslutat": "{vad} — avslutat.",
  "delning.rubrik.fall": "Ärende",
  "delning.rubrik.delat": "Delat ärende",
  "delning.status.avslutat": "Avslutat",
  "delning.status.pagaende": "Diagnos pågår",
  "delning.identitet.arbetsorder": "Arbetsorder",
  "delning.identitet.claim": "Claim",
  "delning.identitet.skadenummer": "Skadenummer",
  "delning.identitet.regnr": "Reg.nr",
  "delning.identitet.vin": "VIN",
  "delning.identitet.miltal": "Mätarställning",
  "delning.identitet.ansvarig": "Ansvarig tekniker",
  "delning.identitet.status": "Status",
  "delning.rubrik.sammanfattning": "Sammanfattning",
  "delning.rubrik.slutsats": "Slutord och motivering",
  "delning.slutsats.ej_faststalld": "Skäl till att orsaken inte kunde fastställas",
  "delning.slutsats.motivering": "Motivering",
  "delning.slutsats.uteslutet": "Uteslutna alternativ",
  "delning.slutsats.atgardsval": "Val av åtgärd",
  "delning.slutsats.kvarstaende": "Kvarstående osäkerhet",
  "delning.rubrik.felbeskrivning": "Kundens felbeskrivning",
  "delning.rubrik.forslag": "Föreslagen åtgärd",
  "delning.forslag.kostnad": "Uppskattad kostnad: {kostnad}",
  "delning.forslag.beslut": "Ditt besked: {beslut}",
  "delning.forslag.via": "(registrerat via {kanal})",
  "delning.forslag.vantar": "Inväntar ditt besked — kontakta verkstaden för att godkänna eller avböja.",
  "delning.beslut.rubrik": "Ditt besked till verkstaden",
  "delning.beslut.godkann": "Godkänn åtgärden",
  "delning.beslut.avboj": "Avböj",
  "delning.beslut.kommentar": "Kommentar (valfri)",
  "delning.beslut.motivering": "Kort motivering (valfri)",
  "delning.beslut.skickar": "Skickar …",
  "delning.beslut.skicka": "Skicka besked",
  "delning.beslut.info":
    "Beskedet bokförs i ärendet och kan inte ändras här — kontakta verkstaden om du ångrar dig.",
  "delning.beslut.godkant": "Godkänt",
  "delning.beslut.avbojt": "Avböjt",
  "delning.beslut.delvis": "Delvis godkänt",
  "delning.beslut.fel.plattform": "Beskedet kan inte lämnas här — kontakta verkstaden.",
  "delning.beslut.fel.registrering": "Beskedet kunde inte registreras — försök igen.",
  "delning.beslut.fel.forbindelse": "Beskedet kunde inte skickas — kontrollera uppkopplingen.",
  "delning.rubrik.laget": "Nuläge",
  "delning.rubrik.video": "Video",
  "delning.rubrik.bilder": "Bilder",
  "delning.rubrik.matningar": "Mätningar",
  "delning.rubrik.tidslinje": "Tidslinje",
  "delning.tidslinje.arbetssprak": "Tidslinjens poster visas ordagrant, på verkstadens arbetsspråk.",
  "delning.rubrik.nasta": "Rekommenderat nästa steg",
  "delning.rubrik.arbetstid": "Arbetstid",
  "delning.fot": "Ärende #{nummer} · påbörjat {datum} · genererat ur ärendeloggen",
  "delning.notis.kund":
    "Skrivskyddad livevy från verkstaden — sidan uppdateras automatiskt när ny information bokförs.",
  "delning.notis.partner":
    "Skrivskyddad livevy (partnernivå) — innehåller tekniska hypoteser, tydligt märkta som overifierade. Uppdateras automatiskt.",
  "delning.notis.intern":
    "Skrivskyddad livevy (intern nivå) — full insyn i ärendet. Uppdateras automatiskt.",
  "delning.hamtar": "Hämtar ärendet …",
  "delning.saknas": "Ärendet är inte tillgängligt. Stäm av länken med verkstaden — delningen kan ha återkallats.",
};
